#'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''' 
#TestCase ID: 
#Description: 
#Author: 
#Date: 
#Version: 

#''''''''''''''''''''AUTOGENERATED CODE - DO NOT MODIFY'''''''''''''''''''' 
import clr,sys,os,time 
from System.Collections.Generic import List
clr.AddReference("MobileScriptingLibrary") 
import MobileScriptingLibrary 
dut = MobileScriptingLibrary.MobileDUT() 
logger = MobileScriptingLibrary.Logger() 
chkpt = MobileScriptingLibrary.CheckPoint() 
config = MobileScriptingLibrary.DeviceConfig() 

#''''''''''''''''''''''''''''''''IMPORTS''''''''''''''''''''''''''''''''''' 
#''''''''''''''''''''''''''''''END IMPORTS''''''''''''''''''''''''''''''''' 

#''''''''''''''''''''''''''''''FOR iOS DEVICE'''''''''''''''''''''''''''''' 
#config.DeviceType = "iOS" 
#config.AppName = "com.google.ios.youtube" 


#''''''''''''''''''''''''''''FOR ANDROID DEVICE'''''''''''''''''''''''''''' 
config.DeviceType = "Android" 
config.AppPackage = "com.bskyb.nowtv.beta"
config.AppActivity = "com.nowtv.view.activity.StartupActivity"
args = sys.argv 
scriptPath = os.path.realpath(__file__) 
dut.Configure(args[1],args[2],args[3],args[4],scriptPath) 
logger.Configure(args[1],args[2],args[3],args[4],scriptPath) 
       
try: 
    if(dut.InitApp(config)): 
        logger.Log("App launched.")
        #dut.TapElement(ElementType,"Element Id",index)

        request = MobileScriptingLibrary.HighPrecisionValidationService.VideoAnalysisRequest()
        deviceInfo = MobileScriptingLibrary.HighPrecisionValidationService.DeviceInfo()
        algorithmList =List[MobileScriptingLibrary.HighPrecisionValidationService.Algorithm]()
        algorithm = MobileScriptingLibrary.HighPrecisionValidationService.Algorithm()
        algorithm.Name = "Histogram"
        algorithm.Params = "eyAgICAicmdiRGV0YWlsc0xpc3QiOiBbewogICAgICAgICJyIjogMTAwLAogICAgICAgICJnIjogMzEsCiAgICAgICAgImIiOiAxNDAsCiAgICAgICAgInBpeGVsQ291bnRUaHJlc2hvbGQiOiA4MAogICAgfSwgewogICAgICAgICJyIjogMjU1LAogICAgICAgICJnIjogMTE2LAogICAgICAgICJiIjogNSwKICAgICAgICAicGl4ZWxDb3VudFRocmVzaG9sZCI6IDgwCiAgICB9LCB7CiAgICAgICAgInIiOiA0MSwKICAgICAgICAiZyI6IDEzOSwKICAgICAgICAiYiI6IDI2LAogICAgICAgICJwaXhlbENvdW50VGhyZXNob2xkIjogODAKICAgIH0sIHsKICAgICAgICAiciI6IDAsCiAgICAgICAgImciOiAxMDEsCiAgICAgICAgImIiOiAyNTUsCiAgICAgICAgInBpeGVsQ291bnRUaHJlc2hvbGQiOiA4MAogICAgfV0sCiAgICAibWFza0RldGFpbHMiOiB7CiAgICAgICAgInhjb3JkIjogNTk2LAogICAgICAgICJ5Y29yZCI6IDI4MCwKICAgICAgICAid2lkdGgiOiA4NSwKICAgICAgICAiaGVpZ2h0IjogNzkKICAgIH0KfQ=="
        algorithmList.Add(algorithm)
        request.Duration = 120
        request.Token = "token"
        request.Algorithms = algorithmList
        request.DeviceInfo = deviceInfo
        response = dut.validator.StartHighPrecisionFrameAnalysis(request)
        time.sleep(20)
        dut.Tap(265,721)
        time.sleep(10)
        dut.Tap(523, 530)
        time.sleep(10)
        dut.Tap(497, 1210)
        time.sleep(10)
        dut.Tap(1625, 966)
        time.sleep(1)
        dut.Tap(1625, 966)
        time.sleep(120)
        logger.Log("Response - " + response.Data.Token)
        statusRequest = MobileScriptingLibrary.HighPrecisionValidationService.VideoAnalysisStatusRequest()
        statusRequest.Token = response.Data.Token
        statusRespose = dut.validator.GetHighPrecisionFrameAnalysisResult(statusRequest)
        dut.CommitTestResult("PASSED")

finally: 
    dut.CloseApp()

#'''''''''''''''''''''''''END AUTOGENERATED CODE''''''''''''''''''''''''''' 
#''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''