#'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''' 
#TestCase ID: 
#Description: 
#Author: 
#Date: 
#Version: 

#''''''''''''''''''''AUTOGENERATED CODE - DO NOT MODIFY'''''''''''''''''''' 
import clr,sys,os,time 
clr.AddReference("MobileScriptingLibrary") 
from System.Collections.Generic import List
import MobileScriptingLibrary 
dut = MobileScriptingLibrary.MobileDUT() 
logger = MobileScriptingLibrary.Logger() 
chkpt = MobileScriptingLibrary.CheckPoint() 
config = MobileScriptingLibrary.DeviceConfig() 

#''''''''''''''''''''''''''''''''IMPORTS''''''''''''''''''''''''''''''''''' 
#''''''''''''''''''''''''''''''END IMPORTS''''''''''''''''''''''''''''''''' 

#''''''''''''''''''''''''''''''FOR iOS DEVICE'''''''''''''''''''''''''''''' 
#config.DeviceType = "iOS" 
#config.AppName = "com.google.ios.youtube" 


#''''''''''''''''''''''''''''FOR ANDROID DEVICE'''''''''''''''''''''''''''' 
config.DeviceType = "Android" 
config.AppPackage = "com.bskyb.skygo" 
config.AppActivity = "com.bskyb.uma.app.bootstrap.BootstrapActivity" 

args = sys.argv 
scriptPath = os.path.realpath(__file__) 
dut.Configure(args[1],args[2],args[3],args[4],scriptPath) 
logger.Configure(args[1],args[2],args[3],args[4],scriptPath) 
       
try: 
    if(dut.InitApp(config)): 
        logger.Log("App launched.") 
        time.sleep(40)
        dut.Tap(528,493)
        time.sleep(20)
        dut.Tap(353,619)
        time.sleep(20)
        for i in range(0, 200):
            reservationRequest = MobileScriptingLibrary.HighPrecisionValidationService.SlotReservationRequest()
            reservationRequest.AlgorithmCount = 1
            reservationResponse = dut.ReserveSlotForHPA(reservationRequest)
            request = MobileScriptingLibrary.HighPrecisionValidationService.VideoAnalysisRequest()
            deviceInfo = MobileScriptingLibrary.HighPrecisionValidationService.DeviceInfo()
            algorithmList =List[MobileScriptingLibrary.HighPrecisionValidationService.Algorithm]()
            algorithm = MobileScriptingLibrary.HighPrecisionValidationService.Algorithm()
            algorithm.Name = "HoughCircles"
            algorithm.Params = "ewoJIm1pc2NUaHJlc2hvbGRzIjogewoJCSJjYW5ueVRocmVzaG9sZDEiOiA3NSwKCQkiY2FubnlUaHJlc2hvbGQyIjogMTAwLAoJCSJob3VnaERwIjogMSwKCQkiaG91Z2hNaW5EaXN0IjogNjAsCgkJImhvdWdoUGFyYW0xIjogODAsCgkJImhvdWdoUGFyYW0yIjogMzcsCgkJImRpc3RUcmFuc2Zvcm1GaWx0ZXJEaXN0IjogMwoJfSwKCSJjaXJjbGVUaHJlc2hvbGRzIjogewoJCSJjaXJjbGVQZXJjZW50YWdlTG93TGltaXQiOiA0NSwKCQkiY2lyY2xlUGVyY2VudGFnZVVwTGltaXQiOiA5MywKCQkiY2lyY2xlUmFkaXVzTG93TGltaXQiOiAzOCwKCQkiY2lyY2xlUmFkaXVzVXBMaW1pdCI6IDUxCgl9LAoJIm1hc2tEZXRhaWxzIjogewoJCSJ4Y29yZCI6IDMwNiwKCQkieWNvcmQiOiA1ODYsCgkJIndpZHRoIjogMTA3LAoJCSJoZWlnaHQiOiAxMDYKCX0KfQ=="
            algorithmList.Add(algorithm)
            request.Duration = 300
            request.Token = reservationResponse.Data.Token
            request.Algorithms = algorithmList
            request.DeviceInfo = deviceInfo
            response = dut.validator.StartHighPrecisionFrameAnalysis(request)
            dut.Tap(416,1416)
            time.sleep(1)
            dut.Tap(609,1672)
            time.sleep(60)
            dut.Tap(416,1416)
            time.sleep(1)
            dut.Tap(335,1683)
            time.sleep(300)
            statusRequest = MobileScriptingLibrary.HighPrecisionValidationService.VideoAnalysisStatusRequest()
            statusRequest.Token = response.Data.Token
            statusRespose = dut.validator.GetHighPrecisionFrameAnalysisResult(statusRequest)
finally: 
    dut.CloseApp()

#'''''''''''''''''''''''''END AUTOGENERATED CODE''''''''''''''''''''''''''' 
#''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
