#'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''' 
#TestCase ID: 
#Description: 
#Author: 
#Date: 
#Version: 

#''''''''''''''''''''AUTOGENERATED CODE - DO NOT MODIFY'''''''''''''''''''' 
import clr,sys,os,time 
clr.AddReference("MobileScriptingLibrary") 
import MobileScriptingLibrary 
dut = MobileScriptingLibrary.MobileDUT() 
logger = MobileScriptingLibrary.Logger() 
chkpt = MobileScriptingLibrary.CheckPoint() 
config = MobileScriptingLibrary.DeviceConfig() 

#''''''''''''''''''''''''''''''''IMPORTS''''''''''''''''''''''''''''''''''' 
#''''''''''''''''''''''''''''''END IMPORTS''''''''''''''''''''''''''''''''' 

#''''''''''''''''''''''''''''''FOR iOS DEVICE'''''''''''''''''''''''''''''' 
#config.DeviceType = "iOS" 
#config.AppName = "com.google.ios.youtube" 


#''''''''''''''''''''''''''''FOR ANDROID DEVICE'''''''''''''''''''''''''''' 
config.DeviceType = "Android" 
config.AppPackage = "com.google.android.youtube" 
config.AppActivity = ".HomeActivity" 

args = sys.argv 
scriptPath = os.path.realpath(__file__) 
dut.Configure(args[1],args[2],args[3],args[4],scriptPath) 
logger.Configure(args[1],args[2],args[3],args[4],scriptPath) 
       
try: 
    if(dut.InitApp(config)): 
        logger.Log("App launched.") 
    reservationRequest = MobileScriptingLibrary.HighPrecisionValidationService.SlotReservationRequest()
    reservationRequest.AlgorithmCount = 1
    reservationResponse = dut.ReserveSlotForHPA(reservationRequest)
    if(reservationResponse.Status):
        request = MobileScriptingLibrary.HighPrecisionValidationService.VideoAnalysisRequest()
        deviceInfo = MobileScriptingLibrary.HighPrecisionValidationService.DeviceInfo()
        algorithmList =List[MobileScriptingLibrary.HighPrecisionValidationService.Algorithm]()
        algorithm = MobileScriptingLibrary.HighPrecisionValidationService.Algorithm()
        algorithm.Name = "VideoFreeze"
        algorithm.IsReferenceBased = True
        algorithm.Params = "jewoJIk1hdGNoU2NvcmUiOiAwLjk5LAoJIk1hc2tEZXRhaWxzIjogewoJCSJ4Y29yZCI6IDE3NiwKCQkieWNvcmQiOiAyMjMsCgkJIndpZHRoIjogMzc4LAoJCSJoZWlnaHQiOiAyNTQKCX0KfQ=="
    #    base64input = base64.b64encode(bytes(json_input), 'utf-8')
    #    algorithm.Params = base64input
        algorithm.MinDuration = 1000
        algorithm.MinTimeGap = 1000
        algorithmList.Add(algorithm)
        request.Duration = 600#Duration in seconds. How many seconds the executor should record the frames.
        request.Token = reservationResponse.Data.Token
        request.Algorithms = algorithmList
        request.DeviceInfo = deviceInfo 
        response = dut.validator.StartHighPrecisionFrameAnalysis(request)
        logger.Log("Response - " + response.Data.Token)
        if (response.Status):
            logger.Log("TRUE")
        #for i in range(0,4):
            #dut.controller.sendCommand("Ok")
            time.sleep(1)
            dut.Tap(315,1699)
            
        time.sleep(400)
        statusRequest = MobileScriptingLibrary.HighPrecisionValidationService.VideoAnalysisStatusRequest()
        statusRequest.Token = response.Data.Token
        statusResponse = dut.validator.GetHighPrecisionFrameAnalysisResult(statusRequest)
        #dut.validator.StopHighPrecisionFrameAnalysis(response.Data.Token)
        logger.Log("StatusRespose - " + str(statusResponse))
        dut.CommitTestResult("PASSED")

        dut.Stop()
        #dut.validator.StopAllHighPrecisionFrameAnalysis()
        #dut.CloseApp() 
        time.sleep(10)

finally: 
    dut.Stop() 

#'''''''''''''''''''''''''END AUTOGENERATED CODE''''''''''''''''''''''''''' 
#''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
