#'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''' 
#TestCase ID: 
#Description: 
#Author: 
#Date: 
#Version: 

#''''''''''''''''''''AUTOGENERATED CODE - DO NOT MODIFY'''''''''''''''''''' 
import clr,sys,os,time, json
clr.AddReference("MobileScriptingLibrary") 
import MobileScriptingLibrary 
dut = MobileScriptingLibrary.MobileDUT() 
logger = MobileScriptingLibrary.Logger() 
chkpt = MobileScriptingLibrary.CheckPoint() 
config = MobileScriptingLibrary.DeviceConfig() 

#''''''''''''''''''''''''''''''''IMPORTS''''''''''''''''''''''''''''''''''' 
#''''''''''''''''''''''''''''''END IMPORTS''''''''''''''''''''''''''''''''' 

#''''''''''''''''''''''''''''''FOR iOS DEVICE'''''''''''''''''''''''''''''' 
#config.DeviceType = "iOS" 
#config.AppName = "com.google.ios.youtube" 


#''''''''''''''''''''''''''''FOR ANDROID DEVICE'''''''''''''''''''''''''''' 
config.DeviceType = "Android" 
config.AppPackage = "com.google.android.youtube" 
config.AppActivity = ".HomeActivity" 

args = sys.argv 
scriptPath = os.path.realpath(__file__) 
dut.Configure(args[1],args[2],args[3],args[4],scriptPath) 
logger.Configure(args[1],args[2],args[3],args[4],scriptPath) 
       
#try: 
#    if(dut.InitApp(config)): 
#        logger.Log("App launched.") 


#finally: 
#    dut.Stop() 

#'''''''''''''''''''''''''END AUTOGENERATED CODE''''''''''''''''''''''''''' 
#''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''


#config = {
#"router_setting": { "name" : "Wifi_channel" , "value": { "band": "2.4GHz", "channel": 3 } },
#"connection_type" : "ssh",
#"connection_params" : {"port":22, "ipaddress":"192.168.30.100", "username":"admin", "password":"Falcon@123"},
#"commands" : "nvram set 'wl0_chanspec=3u';nvram commit;restart_wireless",
#"custom_attributes" : {"execid": args[1]}
#}

config = {
"router_setting": { "name" : "Wifi_channel" , "value": { "band": "2.4GHz", "channel": 3 } },
"connection_type" : "ssh",
"connection_params" : {"port":22, "ipaddress":"192.168.30.102", "username":"admin", "password":"Falcon@123"},
"commands" : "nvram set 'wl0_chanspec=3u';nvram commit;restart_wireless",
"custom_attributes" : {"execid": args[1]}
}

config = json.dumps(config)

while (1):
    logger.Log("Continuous invalid ip call")
    output = dut.testEnvironmentController.ChangeRouterSettings(config)
    logger.Log("ChangeRouterSettings - output:: " + output)


    output = dut.testEnvironmentController.GetRouterStatus(config)
    logger.Log("GetRouterStatus - output:: " + output)

    output = dut.testEnvironmentController.ReleaseRouterSettings(config)
    logger.Log("ReleaseRouterSettings - output:: " + output)
