#''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
#TestScript ID  : FE_STB_API_Constants
#Description    : Constant values for STB API test scripts
#Author         : Arya L
#Date           : 12 Mar 2018, 22 March 2018
#Script Version : 2.0
#''''''''''''''''''''AUTOGENERATED CODE - DO NOT MODIFY''''''''''''''''''''
#''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''

# USER DEFINED VARIALBES AND CONSTANTS
###############################################################################
BUILD_NO = "5.0.17.1"

#Expected API behavior
API_PASS= "api pass"
API_FAIL = "api fail"

#Common valid and Invalid names
FILE_NAME = "testimage"
LONG_NAME = "testimage_abcdefghijklmnopqrstuvwxyz_abcdefghijklmnopqrstuvwxyz_abc\
defghijklmnopqrstuvwxyz_abcdefghijklmnopqrstuvwxyz_abcdefghijklmnopqrstuvwxyz_ab\
cdefghijklmnopqrstuvwxyz"

#Used in CacheImageFromUrl.py and DynamicImageCompare.py
CACHE_VALID_URL = "http://10.47.166.48/TestImage/ImageForDynamicImageCompare.JPG"

#Used in CaptureImage.py and ImageMatch.py
CAP_IMAGE_NAME = "CapturedImage"

DEFAULT_FILTER = "Greyscale"
DEFAULT_LANG = "eng"



#TOLERANCES AND PERCENTAGES
################################################################################
DEFAULT_STR_TOLERANCE = "8"
DEFAULT_INT_TOLERANCE = 8
DEFAULT_PERCENT_MATCH = 97
CAP_DEFAULT_QUALITY = 90
#WaitColorMatch, 21 march 2018
DEFAULT_FLATNESS = 90
DEFAULT_COLOR_TOLERANCE = '[5,5,5]'



#SCREEN NAMES
################################################################################
#getOCRText.py, 14 Mar 2018
GET_OCR_VICTORIA_HOME_SCREEN = "getOcrVictoriaHome"
GET_OCR_SKY_HOME_SCREEN = "getOcrSkyHome"


#COORDINATES
################################################################################
#ImageSearch, 16 march 2018
MAX_X = 0
MAX_Y = 0
MAX_WIDTH = 1920
MAX_HEIGHT = 1080



#ALGORITHAMS
################################################################################
#ImageSearch
SqdiffNormed = 1
CcorrNormed  = 3
default_CcoeffNormed  = 5

#WaitImageMatch and ImageMatch, 16 march 2018
PIXEL_BASED_ALGORITHM = 1
RMSE_ALGORITHM = 2



#TIME CONSTANTS
################################################################################
DEFAULT_SLEEP_DELAY = 3
#Used for all performance APIs
DEFAULT_TIMEOUT = 20
DEFAULT_WAITGAP = 5

DEFAULT_KEY_FIRE_TIME_OUT = 2

#GetScreenTransitionTime, 19 march 2018
START_CAPTURE_ZAP_TIME = 30
PERFORMANCE_TIME_TO_WAIT = 20
PERFORMANCE_INITIAL_DELAY = 2

#GetServerTimeStamp and QuickCapture for TurnOffDUT, 14 march 2018
DEFAULT_WAIT_DELAY = 10
