# ''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
# TestCase ID:
# Description:
# Author:
# Date:
# Version:

# ''''''''''''''''''''AUTOGENERATED CODE - DO NOT MODIFY''''''''''''''''''''
import clr, sys, os, time

clr.AddReference("MobileScriptingLibrary")
import MobileScriptingLibrary

dut = MobileScriptingLibrary.MobileDUT()
logger = MobileScriptingLibrary.Logger()
chkpt = MobileScriptingLibrary.CheckPoint()
config = MobileScriptingLibrary.DeviceConfig()

# ''''''''''''''''''''''''''''''''IMPORTS'''''''''''''''''''''''''''''''''''
# ''''''''''''''''''''''''''''''END IMPORTS'''''''''''''''''''''''''''''''''

# ''''''''''''''''''''''''''''''FOR iOS DEVICE''''''''''''''''''''''''''''''
config.DeviceType = "iOS"
config.AppName = "com.google.ios.youtube"

# ''''''''''''''''''''''''''''FOR ANDROID DEVICE''''''''''''''''''''''''''''
# config.DeviceType = "Android"
# config.AppPackage = "com.google.android.youtube"
# config.AppActivity = ".HomeActivity"

args = sys.argv
scriptPath = os.path.realpath(__file__)
dut.Configure(args[1], args[2], args[3], args[4], scriptPath)
logger.Configure(args[1], args[2], args[3], args[4], scriptPath)

try:
    if (dut.InitApp(config)):
        logger.Log("App launched.")
    chkpt1 = MobileScriptingLibrary.CheckPoint()
    chkpt2 = MobileScriptingLibrary.CheckPoint()
    chkpt1.init("lr_account_title")
    chkpt2.init("lr_trending_icon")
    if (dut.validator.validateCheckPoint((chkpt1))):
        logger.Log("Checkpoint validation 1 - Success!!!")
    else:
        logger.Log("Checkpoint validation 1 - Failure!!!")
    if (dut.validator.validateCheckPoint((chkpt2))):
        logger.Log("IC Checkpoint validation 1 - Success!!!")
    else:
        logger.Log("IC Checkpoint validation 1 - Failure!!!")

    dut.Click(MobileScriptingLibrary.Constants.ElementType.XPath, "//XCUIElementTypeButton", 4)
    # dut.Click(MobileScriptingLibrary.Constants.ElementType.XPath, "//android.widget.ImageView", 3)
    time.sleep(2)
    if (dut.validator.validateCheckPoint((chkpt1))):
        logger.Log("Checkpoint validation 2 - Success!!!")
    else:
        logger.Log("Checkpoint validation 2 - Failure!!!")
    if (dut.validator.validateCheckPoint((chkpt2))):
        logger.Log("IC Checkpoint validation 2 - Success!!!")
    else:
        logger.Log("IC Checkpoint validation 2 - Failure!!!")
finally:
    # dut.Stop()
    pass

# '''''''''''''''''''''''''END AUTOGENERATED CODE'''''''''''''''''''''''''''
# ''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
