# -*- coding: utf-8 -*- 
#'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''' 
#TestCase ID: 
#Description: 
#Author: 
#Date: 
#Version: 

#''''''''''''''''''''AUTOGENERATED CODE - DO NOT MODIFY'''''''''''''''''''' 
import clr,sys,os,time 
clr.AddReference("MobileScriptingLibrary") 
import MobileScriptingLibrary 
dut = MobileScriptingLibrary.MobileDUT() 
logger = MobileScriptingLibrary.Logger() 
chkpt = MobileScriptingLibrary.CheckPoint() 
config = MobileScriptingLibrary.DeviceConfig() 

#''''''''''''''''''''''''''''''''IMPORTS''''''''''''''''''''''''''''''''''' 
#''''''''''''''''''''''''''''''END IMPORTS''''''''''''''''''''''''''''''''' 

#''''''''''''''''''''''''''''''FOR iOS DEVICE'''''''''''''''''''''''''''''' 
#config.DeviceType = "iOS" 
#config.AppName = "com.google.ios.youtube" 


#''''''''''''''''''''''''''''FOR ANDROID DEVICE'''''''''''''''''''''''''''' 
config.DeviceType = "Android" 
config.AppPackage = "com.google.android.youtube" 
config.AppActivity = ".HomeActivity" 

args = sys.argv 
scriptPath = os.path.realpath(__file__) 
dut.Configure(args[1],args[2],args[3],args[4],scriptPath) 
logger.Configure(args[1],args[2],args[3],args[4],scriptPath) 
       
try: 
    if(dut.InitApp(config)): 
        logger.Log("App launched.") 
    
    search_access_id = 'Search'
    search_id = 'com.google.android.youtube:id/search_edit_text'
    ms1 = time.time()*1000.0
    ret = dut.Click(MobileScriptingLibrary.Constants.ElementType.AccessibilityID, search_access_id)
    ms2 = time.time()*1000.0

    logger.Log("Time taken for Click API is >>>> "+str(ms2-ms1))
    logger.Log("Ret value of the API is >>>> "+str(ret))

    time.sleep(2)
    ms1 = time.time()*1000.0
    #ret = dut.SendKeys(MobileScriptingLibrary.Constants.ElementType.Id, search_id, "Learn Spanish Words")
    ret = dut.SendKeys(MobileScriptingLibrary.Constants.ElementType.Id, search_id, "Spanish for Beginners | Spanish")
    ms2 = time.time()*1000.0

    logger.Log("Time taken for SendKeys API is >>>> "+str(ms2-ms1))
    logger.Log("Ret value of the API is >>>> "+str(ret))
    time.sleep(2)
    dut.Tap(308, 400)
    time.sleep(4)
#    ret = dut.Swipe(250, 1250, 250, 5)
#    time.sleep(2)
#    ret = dut.Swipe(250, 1250, 250, 5)
#    time.sleep(2)


    
#    dut.validator.StopCaptureZapFrames()
##WaitOCRMatch
#    refText="llamas?"
#    x_coordinate=196
#    y_coordinate=237
#    width=140
#    height=42
#    timeToWait=20
#    waitGap=5
#    language="spa"
#    #filters = "Greyscale;Black and White"
#    filters=""
#    compType= 1
#    accuracy= 92
#    if(dut.validator.StartCaptureZapFrames(30)):
#        matchTime = dut.validator.WaitOCRMatch(refText,x_coordinate, y_coordinate, width, height,timeToWait,waitGap,language,filters,compType,accuracy)    
#        if(matchTime > 0):
#            logger.Log("WaitOCRMatch Spanish ---- time:" + str(matchTime))
#            logger.Log("WaitOCRMatch Spanish ---- passed")
#            dut.CommitTestResult("Passed")
#        else:
#            logger.Log("WaitOCRMatch Spanish ---- case failed")
#            dut.CommitTestResult("Failed")
#        dut.validator.StopCaptureZapFrames()
#    else:
#        logger.Log("Unable to start frame capture")

#    dut.validator.StopCaptureZapFrames()
##WaitForCheckpoint
#    checkpoints = ['lr_test_spanish_text', 'lr_spanish_multi_line']
##'lr_spanish_mult_filter',
#    for checkpoint in checkpoints:
#        checkpName=checkpoint
#        timeToWait = 40
#        initialDelay = 1 #should be >=0
#        time.sleep(5)
#        if(dut.validator.StartCaptureZapFrames(30)):
#           #key presses or other code
#           out_time = dut.validator.WaitForCheckpoint(checkpName, timeToWait, initialDelay)
#           logger.Log("WaitForCheckpoint(Spanish) ---- time:" + str(out_time))
#           if(out_time > -1):
#               logger.Log("WaitForCheckpoint(Spanish) passed")
#           else:
#               logger.Log("WaitForCheckpoint(Spanish) failed")
#           dut.validator.StopCaptureZapFrames()
#        else:
#           logger.Log("Unable to start frame capture")


#getOCRText
#    x_coordinate=146
#    y_coordinate=197
#    width=174
#    height=45
#    filters = ''
#    language = "spa"
#    ocr_output = dut.validator.getOCRText(x_coordinate, y_coordinate, width, height, filters , language)
#    logger.Log("getOCRText(Spanish) output string : " + ocr_output)
#    if ocr_output == '¿Cómo Te':
#        logger.Log("getOCRText(Spanish) Passed!!!")
#    else:
#        logger.Log("getOCRText(Spanish) Failed!!!")


# validateCheckPoint
    checkpoints = ['lr_test_spanish_text', 'lr_spanish_mult_filter', 'lr_spanish_multi_line']
    for checkpoint in checkpoints:
        checkp = checkpoint
        chkpt.init(checkp)
        if(dut.validator.validateCheckPoint((chkpt))):
            logger.Log("ValidateCheckPoint(Spanish) ---- Passed")
        else:
            logger.Log("ValidateCheckPoint(Spanish) ---- Failed")

#WaitCheckPointMatch
#    checkpoints = ['lr_test_spanish_text', 'lr_spanish_mult_filter', 'lr_spanish_multi_line']
#    for checkpoint in checkpoints:
#        checkpName = checkpoint
#        chkpt.init(checkpName)
#        timeToWait=20
#        waitGap=2
#        if(dut.validator.WaitCheckPointMatch( chkpt,timeToWait,waitGap)):
#            logger.Log("WaitCheckPointMatch -- Spanish Success")
#        else:
#            logger.Log("WaitCheckPointMatch -- Spanish Faillll")

finally:
    #dut.Stop()
    pass

#'''''''''''''''''''''''''END AUTOGENERATED CODE''''''''''''''''''''''''''' 
#''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
