# ''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
# TestCase ID:Xbox_1
# Description: Youtube App palyback and Pause play forward and Rewind
# Author:Mrutyunjaya
# Date:04/09/2018
# Version:1.0

# ''''''''''''''''''''AUTOGENERATED CODE - DO NOT MODIFY''''''''''''''''''''
import clr
import sys
import os
import time
clr.AddReference("ScriptingLibrary")
import ScriptingLibrary
dut = ScriptingLibrary.DUT()
logger = ScriptingLibrary.Logger()
chkpt = ScriptingLibrary.CheckPoint()
testResult = ScriptingLibrary.TestResult()
args = sys.argv
scriptPath = os.path.realpath(__file__)
remoteFiringType = "IR"
dut.Configure(args[1], args[2], args[3], args[4], scriptPath, remoteFiringType)
logger.Configure(args[1], args[2], args[3], args[4], scriptPath)

# ''''''''''''''''''''''''''''''''IMPORTS''''''''''''''''''''''''''''''''''
# ''''''''''''''''''''''''''''''END IMPORTS''''''''''''''''''''''''''''''''

#'''''''''''''''''''''''''END AUTOGENERATED CODE'''''''''''''''''''''''''''
# ''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''

video_x = 136
video_y = 111
video_w = 619
video_h = 459
timeout = 20
waitGap = 5
tolerance = "10"
image_format = "BMP"
checkpName = "Xbox_YouTube"
imageName = "test"

# '''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''

def main():
    try:
        # Press Xbox Button to Launch the Home page
        dut.controller.sendCommand("XboxHome")
        # API Call :- QuickCapture
        imagePath = dut.validator.QuickCapture(imageName)
        time.sleep(20)
        # Checkpoint initialization
        chkpt.init("Xbox_Home")
        # Validate checkpoint for Youtube APP
        if(dut.validator.validateCheckPoint((chkpt))):
            dut.CommitStepResult("Xbox Home launch", "PASSED")
            logger.Log("Xbox home App has launched successfully")
            time.sleep(5)
            # STB API :- QuickCaptureEx Call
            imagePath = dut.validator.QuickCaptureEx(imageName, image_format)
            dut.CommitStepResult("YouTube Launch QuickCaptureEx", "PASSED")
            time.sleep(5)
            dut.controller.sendCommand("Down")
            time.sleep(3)
            dut.controller.sendCommand("Down")
            chkpt.init(checkpName)
            if (dut.validator.WaitCheckPointMatch(chkpt, 30, 5)):
                dut.CommitStepResult("Wait Checkpoint Match", "PASSED")              
                dut.controller.sendCommand("OK")
                time.sleep(20)
                chkpt.init("Xbox_YouTubeHomeScreen")
                if(dut.validator.validateCheckPoint((chkpt))):
                    logger.Log("YouTube Home Screen reached")
                    dut.CommitTestResult("PASSED")
                    dut.controller.sendCommand("OK")
                    time.sleep(20)
                else:
                    logger.Error("Youtube Wrong Screen reached")
                    dut.CommitTestResult("FAILED")
                # checking motion detection after youtube launch
                if(dut.validator.DetectMotion(video_x, video_y, video_w, video_h, timeout, waitGap, tolerance)):
                    logger.Log("Video Playback started successfully")
                    dut.CommitTestResult("PASSED")
                    dut.controller.sendCommand("FastForward")
                    time.sleep(5)
                    dut.controller.sendCommand("FastForward")
                    time.sleep(5)
                    dut.controller.sendCommand("PlayPause")
                    time.sleep(5)
                    dut.controller.sendCommand("PlayPause")
                    time.sleep(5)
                    dut.controller.sendCommand("PlayPause")
                    time.sleep(5)
                    dut.controller.sendCommand("Rewind")                    
                    time.sleep(3)
                    dut.controller.sendCommand("Rewind")
                else:
                    logger.Log("VideoPlayback Failed")
                    dut.CommitTestResult("FAILED")
            else:
                dut.CommitStepResult("Wait Checkpoint Match", "FAILED")
            dut.controller.sendCommand("XboxHome")
            dut.controller.sendCommand("OK")
        else:
            logger.Log("Xbox Home launch failed in Xbox")
            dut.CommitStepResult("Xbox home Launch", "FAILED")
            dut.CommitTestResult("FAILED")
    except BaseException as e:
        print str(e)
        logger.Log("Exception raised in main function.")
        dut.CommitTestResult("ERROR")
    finally:
        time.sleep(10)


if __name__ == "__main__":
    main()
