#''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
#TestCase ID:
#Description:
#Author:
#Date:
#Version:

#''''''''''''''''''''AUTOGENERATED CODE - DO NOT MODIFY''''''''''''''''''''
import clr,sys,os,time, json
clr.AddReference("ScriptingLibrary")
import ScriptingLibrary
dut = ScriptingLibrary.DUT()
logger = ScriptingLibrary.Logger()
chkpt = ScriptingLibrary.CheckPoint()
testResult = ScriptingLibrary.TestResult()
args = sys.argv
scriptPath = os.path.realpath(__file__)
remoteFiringType = "IR"
dut.Configure(args[1],args[2],args[3],args[4],scriptPath,remoteFiringType)
logger.Configure(args[1],args[2],args[3],args[4],scriptPath)

#''''''''''''''''''''''''''''''''IMPORTS''''''''''''''''''''''''''''''''''
#''''''''''''''''''''''''''''''END IMPORTS''''''''''''''''''''''''''''''''

#'''''''''''''''''''''''''END AUTOGENERATED CODE'''''''''''''''''''''''''''
#''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
config = {
"router_setting": { "name" : "Wifi_channel" , "value": { "band": "2.4GHz", "channel":4} },
"connection_type" : "ssh",
"connection_params" : {"port":22, "ipaddress":"192.168.30.100", "username":"admin", "password":"Falcon@123"},
"commands" : "nvram set 'wl0_chanspec=4u';nvram commit;restart_wireless",
"custom_attributes" : {"execid": args[1]}
}
config = json.dumps(config)
dut.testEnvironmentController.ChangeRouterSettings(config)
logger.Log("Check: 2G - 3")
time.sleep(10)
output = dut.testEnvironmentController.GetRouterStatus(config)

output = dut.testEnvironmentController.ReleaseRouterSettings(config)
output = dut.testEnvironmentController.GetRouterStatus(config)