#''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
#Author        : Arathy PS
#Description   : Check whether the You tube lauch is working & video is playing
#Date          : 23 Jan 2018
#FE_Version    : 5.0.7

#''''''''''''''''''''AUTOGENERATED CODE - DO NOT MODIFY''''''''''''''''''''
import clr, sys, os, time, re,timeit
clr.AddReference("MobileScriptingLibrary")
import MobileScriptingLibrary
dut = MobileScriptingLibrary.MobileDUT()
logger = MobileScriptingLibrary.Logger()
scriptPath = os.path.realpath(__file__)
args = sys.argv
dut.Configure(args[1],args[2],args[3],args[4],scriptPath)
logger.Configure(args[1],args[2],args[3],args[4],scriptPath)
#''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''

chkpt = MobileScriptingLibrary.CheckPoint()
config = MobileScriptingLibrary.DeviceConfig()
config.DeviceType = "Android"

#youtube
config.AppPackage = "com.google.android.youtube"
config.AppActivity = "com.google.android.youtube.HomeActivity"
#'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
#variable declaration

time.sleep(60)