#''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
#TestCase ID:
#Description:
#Author:
#Date:
#Version:

#''''''''''''''''''''AUTOGENERATED CODE - DO NOT MODIFY''''''''''''''''''''
import clr,sys,os,time
clr.AddReference("ScriptingLibrary")
import ScriptingLibrary
dut = ScriptingLibrary.DUT()
logger = ScriptingLibrary.Logger()
chkpt = ScriptingLibrary.CheckPoint()
testResult = ScriptingLibrary.TestResult()
args = sys.argv
scriptPath = os.path.realpath(__file__)
remoteFiringType = "BLEV2"
dut.Configure(args[1],args[2],args[3],args[4],scriptPath,remoteFiringType)
logger.Configure(args[1],args[2],args[3],args[4],scriptPath)

#''''''''''''''''''''''''''''''''IMPORTS''''''''''''''''''''''''''''''''''
#''''''''''''''''''''''''''''''END IMPORTS''''''''''''''''''''''''''''''''

#'''''''''''''''''''''''''END AUTOGENERATED CODE'''''''''''''''''''''''''''
#''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''

dut.navigator.NavigateTo ("EXPLORAR",1,False)
for i in range (0, 10):
    logger.Log("Count : " + str(i))
    dut.controller.sendCommand("KEY_F10")
    logger.Log("Menu key fired")
    time.sleep(3)
    dut.controller.sendCommand("KEY_DOWN")
    
    chkpt.init("BLE_IC")
    if(dut.validator.validateCheckPoint((chkpt))):
        logger.Log("NOS MENU Screen Launched")
    else:
        logger.Log("Key firing failed. NOS MENU Screen is missing")
