#''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
#TestCase ID:
#Description:
#Author:
#Date:
#Version:

#''''''''''''''''''''AUTOGENERATED CODE - DO NOT MODIFY''''''''''''''''''''
import clr,sys,os,time
clr.AddReference("ScriptingLibrary")
import ScriptingLibrary
dut = ScriptingLibrary.DUT()
logger = ScriptingLibrary.Logger()
chkpt = ScriptingLibrary.CheckPoint()
testResult = ScriptingLibrary.TestResult()
args = sys.argv
scriptPath = os.path.realpath(__file__)
remoteFiringType = "IP"
dut.Configure(args[1],args[2],args[3],args[4],scriptPath,remoteFiringType)
logger.Configure(args[1],args[2],args[3],args[4],scriptPath)

#''''''''''''''''''''''''''''''''IMPORTS''''''''''''''''''''''''''''''''''
#''''''''''''''''''''''''''''''END IMPORTS''''''''''''''''''''''''''''''''

#'''''''''''''''''''''''''END AUTOGENERATED CODE'''''''''''''''''''''''''''
#''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
for i in range(0, 1000):
	dut.controller.sendCommand("Down")
	dut.validator.QuickCapture("1")
	dut.controller.sendCommand("Down")
	dut.validator.QuickCapture("2")
	dut.controller.sendCommand("Down")
	dut.validator.QuickCapture("3")
	dut.controller.sendCommand("Down")
	dut.validator.QuickCapture("4")


	dut.controller.sendCommand("Home")
	dut.validator.QuickCapture("1")
	dut.controller.sendCommand("Up")
	dut.validator.QuickCapture("2")
	dut.controller.sendCommand("Right")
	dut.validator.QuickCapture("3")
	dut.controller.sendCommand("Left")
	dut.validator.QuickCapture("4")
