#''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
#TestCase ID:
#Description:
#Author:
#Date:
#Version:

#''''''''''''''''''''AUTOGENERATED CODE - DO NOT MODIFY''''''''''''''''''''
import clr,sys,os,time
clr.AddReference("ScriptingLibrary")
import ScriptingLibrary
dut = ScriptingLibrary.DUT()
logger = ScriptingLibrary.Logger()
chkpt = ScriptingLibrary.CheckPoint()
testResult = ScriptingLibrary.TestResult()
args = sys.argv
scriptPath = os.path.realpath(__file__)
remoteFiringType = "IR"
dut.Configure(args[1],args[2],args[3],args[4],scriptPath,remoteFiringType)
logger.Configure(args[1],args[2],args[3],args[4],scriptPath)

#''''''''''''''''''''''''''''''''IMPORTS''''''''''''''''''''''''''''''''''
#''''''''''''''''''''''''''''''END IMPORTS''''''''''''''''''''''''''''''''

#'''''''''''''''''''''''''END AUTOGENERATED CODE'''''''''''''''''''''''''''
#''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''


#Provide valid parameters
x_coordinate=176
y_coordinate=319
width=191
height=57
filters = "Greyscale"


English = "eng"
Italian  = "ita"
Portuguese  = "por"
German  = "deu"
Spanish  = "spa"
Chinese   = "chi_sim"
hindi = "hin"

#for i in range (0,50):
while 1:
    imagePath = dut.validator.QuickCapture("testIm")
    string = dut.validator.getOCRText(x_coordinate, y_coordinate, width, height, filters , English)
    logger.Log( "string:" + string)


    string = dut.validator.getOCRText(x_coordinate, y_coordinate, width, height, filters , English)
    logger.Log( "string:" + string)

    string = dut.validator.getOCRText(x_coordinate, y_coordinate, width, height, filters , Italian)
    logger.Log( "string:" + string)

    string = dut.validator.getOCRText(x_coordinate, y_coordinate, width, height, filters , Portuguese)
    logger.Log( "string:" + string) 
    string = dut.validator.getOCRText(x_coordinate, y_coordinate, width, height, filters , German)
    logger.Log( "string:" + string)

    string = dut.validator.getOCRText(x_coordinate, y_coordinate, width, height, filters , Spanish)
    logger.Log( "string:" + string)

    string = dut.validator.getOCRText(x_coordinate, y_coordinate, width, height, filters , Chinese)
    logger.Log( "string:" + string)
    imagePath = dut.validator.QuickCapture("testIm")
    dut.controller.sendCommand("Home")