# ''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
# TestCase ID:
# Description:
# Author:
# Date:
# Version:

# ''''''''''''''''''''AUTOGENERATED CODE - DO NOT MODIFY''''''''''''''''''''
import clr
import sys
import os
import time, datetime
from System.Collections.Generic import List
clr.AddReference("ScriptingLibrary")
import ScriptingLibrary
dut = ScriptingLibrary.DUT()
logger = ScriptingLibrary.Logger()
chkpt = ScriptingLibrary.CheckPoint()
testResult = ScriptingLibrary.TestResult()
args = sys.argv
scriptPath = os.path.realpath(__file__)
remoteFiringType = "IR"
dut.Configure(args[1], args[2], args[3], args[4], scriptPath, remoteFiringType)
logger.Configure(args[1], args[2], args[3], args[4], scriptPath)

# ''''''''''''''''''''''''''''''''IMPORTS''''''''''''''''''''''''''''''''''
# ''''''''''''''''''''''''''''''END IMPORTS''''''''''''''''''''''''''''''''

#'''''''''''''''''''''''''END AUTOGENERATED CODE'''''''''''''''''''''''''''
# ''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
for i in range (25):
	logger.Log("Loop " + str(i))
	dut.controller.sendCommand("Home")
	time.sleep(5)
	dut.controller.sendCommand("Down")
	time.sleep(1)
	dut.controller.sendCommand("Down")
	time.sleep(1)
	dut.controller.sendCommand("Down")
	time.sleep(1)
	dut.controller.sendCommand("Right")
	time.sleep(5)
	dut.controller.cacheCommand("Home")

	resp = ScriptingLibrary.APIResponse.ResponseData()
	inputParam = ScriptingLibrary.HighPrecisionValidationService.MotionParams()
	inputParam.x_cord = 1
	inputParam.y_cord = 30
	inputParam.width = 1825
	inputParam.height = 1050
	inputParam.sensitivity = 50
	lstInputParam = List[ScriptingLibrary.HighPrecisionValidationService.MotionParams]()
	lstInputParam.Add(inputParam)
	inputParam.x_cord = 132
	inputParam.y_cord = 544
	inputParam.width = 129
	inputParam.height = 141
	inputParam.sensitivity = 7
	lstInputParam.Add(inputParam)
	inputParam.x_cord = 500
	inputParam.y_cord = 544
	inputParam.width = 129
	inputParam.height = 41
	inputParam.sensitivity = 10
	lstInputParam.Add(inputParam)
	inputParam.x_cord = 632
	inputParam.y_cord = 544
	inputParam.width = 829
	inputParam.height = 541
	inputParam.sensitivity = 17
	lstInputParam.Add(inputParam)

	inputParam.enableAggressiveMode = False 
	resp = dut.validator.DetectScreenChange(60, lstInputParam)
	logger.Log("Duration 0 " + str(resp.MotionData[0].Duration))
	dut.CommitStepResult("Duration 0", str(resp.MotionData[0].Duration))
	logger.Log("Duration 1 " + str(resp.MotionData[1].Duration))
	dut.CommitStepResult("Duration 1", str(resp.MotionData[1].Duration))
	logger.Log("Duration 2 " + str(resp.MotionData[2].Duration))
	dut.CommitStepResult("Duration 2", str(resp.MotionData[2].Duration))
	logger.Log("Duration 3 " + str(resp.MotionData[3].Duration))
	dut.CommitStepResult("Duration 3", str(resp.MotionData[3].Duration))
