#'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''' 
#TestCase ID: 
#Description: 
#Author: 
#Date: 
#Version: 

#''''''''''''''''''''AUTOGENERATED CODE - DO NOT MODIFY'''''''''''''''''''' 
import clr,sys,os,time 
from System.Collections.Generic import List
clr.AddReference("MobileScriptingLibrary") 
import MobileScriptingLibrary 
dut = MobileScriptingLibrary.MobileDUT() 
logger = MobileScriptingLibrary.Logger() 
chkpt = MobileScriptingLibrary.CheckPoint() 
config = MobileScriptingLibrary.DeviceConfig() 

#''''''''''''''''''''''''''''''''IMPORTS''''''''''''''''''''''''''''''''''' 
#''''''''''''''''''''''''''''''END IMPORTS''''''''''''''''''''''''''''''''' 

#''''''''''''''''''''''''''''''FOR iOS DEVICE'''''''''''''''''''''''''''''' 
config.DeviceType = "iOS" 
config.AppName = "com.google.ios.youtube" 


#''''''''''''''''''''''''''''FOR ANDROID DEVICE'''''''''''''''''''''''''''' 
#config.DeviceType = "Android" 
#config.AppPackage = "com.google.android.youtube" 
#config.AppActivity = ".HomeActivity" 

args = sys.argv 
scriptPath = os.path.realpath(__file__) 
dut.Configure(args[1],args[2],args[3],args[4],scriptPath) 
logger.Configure(args[1],args[2],args[3],args[4],scriptPath) 
try: 
    if(dut.InitApp(config)): 
        logger.Log("App launched.") 
        time.sleep(15)
        #dut.Tap(500,500)
        inputParam = MobileScriptingLibrary.HighPrecisionValidationService.MotionParams()
        tapData = MobileScriptingLibrary.Models.TapData()
        tapData.type=MobileScriptingLibrary.Constants.ElementType.XPath
        tapData.value="//XCUIElementTypeScrollView[@name='id.ui.browse.tab.content']/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeCollectionView/XCUIElementTypeCell[2]"#"//android.widget.ImageView[@content-desc='Search']"
        tapDataList = List[MobileScriptingLibrary.Models.TapData]()
        tapDataList.Add(tapData)
        #tapData.x_Cord = 250
        #tapData.y_Cord = 250
        #dut.Tap(500,500)
        #Second tap Data List
        #tapData = MobileScriptingLibrary.Models.TapData()
        #tapData.type=MobileScriptingLibrary.Constants.ElementType.XPath
        #tapData.value="//android.widget.ImageView[@content-desc='Video']"
        #tapDataList = List[MobileScriptingLibrary.Models.TapData]()
        #tapDataList.Add(tapData)
        #print type(inputParam)
        inputParam.x_cord = 209#0
        inputParam.y_cord = 158#0
        inputParam.width = 371#500
        inputParam.height = 288#500
        inputParam.sensitivity = 3
        inputParam.enableAggrassiveMode = True
        lstInputParam =List[MobileScriptingLibrary.HighPrecisionValidationService.MotionParams]()
        lstInputParam.Add(inputParam)
        inputParam.x_cord = 209#109
        inputParam.y_cord = 158#890
        inputParam.width = 371#515#500
        inputParam.height = 288#206#500
        inputParam.sensitivity = 3
        inputParam.enableAggrassiveMode = True
        lstInputParam.Add(inputParam)    
        #print type(lstInputParam)
        stepcommit="valid arguments"
        expected="Motion Detected"
       
        resp = dut.validator.GetScreenTransitions(dut,50,lstInputParam, tapDataList,)            

finally: 
    #dut.Stop() 
    time.sleep(5)

#'''''''''''''''''''''''''END AUTOGENERATED CODE''''''''''''''''''''''''''' 
#''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
