#'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''' 
#TestCase ID: 
#Description: 
#Author: 
#Date: 
#Version: 

#''''''''''''''''''''AUTOGENERATED CODE - DO NOT MODIFY'''''''''''''''''''' 
import clr,sys,os,time 
from System.Collections.Generic import List
clr.AddReference("MobileScriptingLibrary") 
import MobileScriptingLibrary 
dut = MobileScriptingLibrary.MobileDUT() 
logger = MobileScriptingLibrary.Logger() 
chkpt = MobileScriptingLibrary.CheckPoint() 
config = MobileScriptingLibrary.DeviceConfig() 

#''''''''''''''''''''''''''''''''IMPORTS''''''''''''''''''''''''''''''''''' 
#''''''''''''''''''''''''''''''END IMPORTS''''''''''''''''''''''''''''''''' 

#''''''''''''''''''''''''''''FOR ANDROID DEVICE'''''''''''''''''''''''''''' 
config.DeviceType = "Android" 
config.AppPackage = "com.google.android.youtube" 
config.AppActivity = ".HomeActivity" 


args = sys.argv 
scriptPath = os.path.realpath(__file__) 
dut.Configure(args[1],args[2],args[3],args[4],scriptPath) 
logger.Configure(args[1],args[2],args[3],args[4],scriptPath) 

for i in range (1000):
	imagePath = dut.validator.QuickCapture("tet" + str(i))
	logger.Log("Loop " + str(i))
	try: 
		if(dut.InitApp(config)): 
			lstInputParam =List[MobileScriptingLibrary.HighPrecisionValidationService.MotionParams]()
			logger.Log("App launched.") 
			time.sleep(5);
			
			tapData = MobileScriptingLibrary.Models.TapData()
			tapData.type=MobileScriptingLibrary.Constants.ElementType.XPath
			tapData.x_Cord = 241
			tapData.y_Cord = 370
			tapDataList = List[MobileScriptingLibrary.Models.TapData]()
			tapDataList.Add(tapData)
			
			inputParam1 = MobileScriptingLibrary.HighPrecisionValidationService.MotionParams()
			inputParam1.x_cord = 0
			inputParam1.y_cord = 0
			inputParam1.width = 500
			inputParam1.height = 500
			inputParam1.sensitivity = 3
			inputParam1.enableAggressiveMode = True 			
			lstInputParam.Add(inputParam1)
			
			inputParam2 = MobileScriptingLibrary.HighPrecisionValidationService.MotionParams()
			inputParam2.x_cord = 0
			inputParam2.y_cord = 0
			inputParam2.width = 500
			inputParam2.height = 500
			inputParam2.sensitivity = 3
			inputParam2.enableAggressiveMode = True 
			lstInputParam.Add(inputParam2) 
			
			if(dut.Click(MobileScriptingLibrary.Constants.ElementType.ClassName,"android.widget.ImageView",2)):
				dut.CommitStepResult("Click on Search","PASSED")
				time.sleep(3)                
				dut.SendKeys(MobileScriptingLibrary.Constants.ElementType.Id, "com.google.android.youtube:id/search_edit_text","MasterChef Australia")
				time.sleep(3)
				dut.SendAndroidKeyCode ("Keycode_ENTER")
				time.sleep(2)   
			resp = dut.validator.GetScreenTransitions(dut,30,lstInputParam, tapDataList)
			if resp is not None and resp.MotionData is not None :
				for i in resp.MotionData:
					logger.Log("Duration " + str(i.Duration))
					dut.CommitStepResult("Duration ", str(i.Duration))
			else:
				logger.Log("Unable to Launch DetectMotionExecutor")
				dut.CommitStepResult("Duration ","FAILED")
	finally: 
		dut.Stop() 

#'''''''''''''''''''''''''END AUTOGENERATED CODE''''''''''''''''''''''''''' 
#''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
