# -*- coding: utf-8 -*-
#''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
#TestCase ID:
#Description:
#Author:
#Date:
#Version:

#''''''''''''''''''''AUTOGENERATED CODE - DO NOT MODIFY''''''''''''''''''''
import clr,sys,os,time
clr.AddReference("ScriptingLibrary")
import ScriptingLibrary
dut = ScriptingLibrary.DUT()
logger = ScriptingLibrary.Logger()
chkpt = ScriptingLibrary.CheckPoint()
testResult = ScriptingLibrary.TestResult()
args = sys.argv
scriptPath = os.path.realpath(__file__)
remoteFiringType = "IR"
dut.Configure(args[1],args[2],args[3],args[4],scriptPath,remoteFiringType)
logger.Configure(args[1],args[2],args[3],args[4],scriptPath)

#''''''''''''''''''''''''''''''''IMPORTS''''''''''''''''''''''''''''''''''
#''''''''''''''''''''''''''''''END IMPORTS''''''''''''''''''''''''''''''''

#'''''''''''''''''''''''''END AUTOGENERATED CODE'''''''''''''''''''''''''''
#''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
English = "eng"
Italian  = "ita"
Portuguese  = "por"
German  = "deu"
Spanish  = "spa"
Chinese   = "chi_sim"
Hindi = "hin"


#Italian
#To reach Pubblicita
#dut.controller.sendCommand("Home")
#dut.controller.sendCommand("Up")
#dut.controller.sendCommand("Right")
#dut.controller.sendCommand("Up")
#dut.controller.sendCommand("Up")

# GERMAN - Nav to test 
#dut.controller.sendCommand("Up")
#dut.controller.sendCommand("Right")
#dut.controller.sendCommand("Down")
#dut.controller.sendCommand("Down")


#Portuguese - nav to Copyrights of NOS box

#x_coordinate= 1010
#y_coordinate= 242
#width= 215
#height= 55
##filters ="Contrast:0;Black&White;Resize:2"
##filters = "Resize:2;Resize:2"
#filters ="Contrast:0, Black&White, Resize:2"
##filters ="Blur:80"
#language = "ita"

#Multiline
#x_coordinate= 146
#y_coordinate= 468
#width= 449
#height= 171
#filters = "Greyscale"
#language = "ita" 

#German
#x_coordinate= 1010
#y_coordinate= 242
#width= 215
#height= 55
#filters = "Greyscale"
#language = "deu"

#text = "Pubblicit"



#text = "Display-Auflösung"
#x_coordinate= 184
#y_coordinate= 245
#width= 352
#height= 51
Nofilters =""


text = "Einstellungen für"
x_coordinate= 170
y_coordinate= 450
width= 334
height= 63

multiFilters ="Contrast:0;Black&White;Resize:2"
#filters = "Resize:2;Resize:2"
#Wrongfilters ="Contrast:0, Black&White, Resize:2"#wrong FORMAT


#port
x_coordinate= 687
y_coordinate= 657
width= 112
height= 38

text = "Copyrights"
x_coordinate= 801
y_coordinate= 201
width= 286
height= 79


#Spanish
text = "Español"
x_coordinate= 453
y_coordinate= 881
width= 173
height= 66


#Spanish
text = "火车站"
x_coordinate= 599
y_coordinate= 619
width= 180
height= 67


#Hindi
text = "वर्णमाला"
x_coordinate= 799
y_coordinate= 538
width= 335
height= 100


#Hindi
text = "वर्णमाला"
x_coordinate= 820
y_coordinate= 549
width= 306
height= 94



#filters = multiFilters
filters = Nofilters
filters = "Contrast:51"
language = Hindi


#2019-03-05 16:13:35,618 INFO  - string read is :火车站

for i in range (0,5):
    string = dut.validator.getOCRText(x_coordinate, y_coordinate, width, height, filters , language)
    logger.Log( "string read is :" + string)
    if text == string:
        dut.CommitStepResult("Read" + str(i),"PASSED")
    else:
        dut.CommitStepResult("Read" + str(i),"Failed")
