#''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
#TestCase ID:
#Description:
#Author:
#Date:
#Version:

#''''''''''''''''''''AUTOGENERATED CODE - DO NOT MODIFY''''''''''''''''''''
import clr,sys,os,time
clr.AddReference("ScriptingLibrary")
import ScriptingLibrary
dut = ScriptingLibrary.DUT()
logger = ScriptingLibrary.Logger()
chkpt = ScriptingLibrary.CheckPoint()
testResult = ScriptingLibrary.TestResult()
args = sys.argv
scriptPath = os.path.realpath(__file__)
remoteFiringType = "IR"
#remoteFiringType = "IP"
dut.Configure(args[1],args[2],args[3],args[4],scriptPath,remoteFiringType)
logger.Configure(args[1],args[2],args[3],args[4],scriptPath)

#''''''''''''''''''''''''''''''''IMPORTS''''''''''''''''''''''''''''''''''
#''''''''''''''''''''''''''''''END IMPORTS''''''''''''''''''''''''''''''''

#'''''''''''''''''''''''''END AUTOGENERATED CODE'''''''''''''''''''''''''''
#''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''

ItalianDict = ["5120_OCR_ITA_SINGLE_NoFil", "5120_OCR_ITA_SINGLE", "5120_OCR_ITA_SINGLE_MULTIFIL", "5120_OCR_ITA_Multi_NoFil", "5120_OCR_ITA_MULTI", "5120_OCR_ITA_MULTI_MULTIFIL"]
#Provide valid parameters
ItalianDict = ["5120_OCR_ITA_SINGLE_NoFil"]
ItalianDict = ["5120_OCR_ITA_SINGLE_Long_NoFil"]
PortugueseDict = ["5120_OCR_POR_SINGLE_NoFil", "5120_OCR_POR_SINGLE_MULTIFIL", "5120_OCR_POR_Multi_NoFil", "5120_OCR_POR_MULTI_MULTIFIL"]
#PortugueseDict = ["5120_OCR_POR_SINGLE_NoFil", "5120_OCR_POR_SINGLE_MULTIFIL"]
germanDict  = ["5120_OCR_GER_SINGLE_NoFil", "5120_OCR_GER_SINGLE", "5120_OCR_GER_SINGLE_MULTIFIL", "5120_GER_ITA_Multi_NoFil", "5120_OCR_GER_MULTI", "5120_OCR_GER_MULTI_MULTIFIL"]

spanishDict  = ["5120_OCR_SPA_SINGLE", "5120_OCR_SPA_SINGLE_MULTIFIL", "5120_GER_SPA_Multi_NoFil", "5120_GER_SPA_Multi_singleFil", "5120_OCR_SPA_MULTI_MULTIFIL" ]
chineseDict  = ["5120_OCR_CHI_SINGLE",]# "5120_OCR_SPA_SINGLE_MULTIFIL", "5120_GER_SPA_Multi_NoFil", "5120_OCR_SPA_MULTI_MULTIFIL" ]
#spanishDict  = ["5120_OCR_SPA_SINGLE",]
hinDict = ["5120_OCR_HIN_SING"]
PortugueseDict = ["5120_OCR_POR_SINGLE_NoFil"]
langDict = spanishDict


timeToWait = 40
duration = timeToWait + 10
initialDelay = 1 #should be >=0
#dut.validator.StopCaptureZapFrames()
for i in langDict:
    checkpName = i
    stat = dut.validator.StartCaptureZapFrames(duration)
    logger.Log("ret" + str(stat))
    if stat:   
        
        #key presses or other code
        #dut.controller.sendCommand("Down")

        timeD = dut.validator.GetScreenTransitionTime(checkpName, timeToWait, initialDelay)
        time.sleep(4)
        if(timeD >= 0):
            logger.Log("time:" + str(timeD))
            logger.Log("Test case passed")
        else:
            logger.Log("Test case failed")
            dut.validator.StopCaptureZapFrames()
    else:
        logger.Log("Unable to start frame capture")

    #dut.controller.sendCommand("Up")
