#'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''' 
#TestCase ID: 
#Description: 
#Author: 
#Date: 
#Version: 

#''''''''''''''''''''AUTOGENERATED CODE - DO NOT MODIFY'''''''''''''''''''' 
import clr,sys,os,time 
from System.Collections.Generic import List 
clr.AddReference("ScriptingLibrary") 
import ScriptingLibrary 
dut = ScriptingLibrary.DUT() 
logger = ScriptingLibrary.Logger() 
chkpt = ScriptingLibrary.CheckPoint() 
testResult = ScriptingLibrary.TestResult() 
args = sys.argv 
scriptPath = os.path.realpath(__file__) 
remoteFiringType = "IP" 
dut.Configure(args[1],args[2],args[3],args[4],scriptPath,remoteFiringType) 
logger.Configure(args[1],args[2],args[3],args[4],scriptPath) 

#''''''''''''''''''''''''''''''''IMPORTS'''''''''''''''''''''''''''''''''' 
#''''''''''''''''''''''''''''''END IMPORTS'''''''''''''''''''''''''''''''' 

#'''''''''''''''''''''''''END AUTOGENERATED CODE''''''''''''''''''''''''''' 
#'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''' 
request = ScriptingLibrary.HighPrecisionValidationService.VideoAnalysisRequest() 
deviceInfo = ScriptingLibrary.HighPrecisionValidationService.DeviceInfo() 
algorithmList =List[ScriptingLibrary.HighPrecisionValidationService.Algorithm]() 
algorithm = ScriptingLibrary.HighPrecisionValidationService.Algorithm() 
reservationRequest = ScriptingLibrary.HighPrecisionValidationService.SlotReservationRequest()
reservationRequest.AlgorithmCount = 1
reservationResponse = dut.ReserveSlotForHPA(reservationRequest)
algorithm.Name = "Histogram" 
#buffering (towards right)
#algorithm.Params = "eyAgICAicmdiRGV0YWlsc0xpc3QiOiBbewogICAgICAgICJyIjogMTAwLAogICAgICAgICJnIjogMzEsCiAgICAgICAgImIiOiAxNDAsCiAgICAgICAgInBpeGVsQ291bnRUaHJlc2hvbGQiOiA1MAogICAgfSwgewogICAgICAgICJyIjogMjU1LAogICAgICAgICJnIjogMTE2LAogICAgICAgICJiIjogNSwKICAgICAgICAicGl4ZWxDb3VudFRocmVzaG9sZCI6IDUwCiAgICB9LCB7CiAgICAgICAgInIiOiA0MSwKICAgICAgICAiZyI6IDEzOSwKICAgICAgICAiYiI6IDI2LAogICAgICAgICJwaXhlbENvdW50VGhyZXNob2xkIjogNTAKICAgIH0sIHsKICAgICAgICAiciI6IDAsCiAgICAgICAgImciOiAxMDEsCiAgICAgICAgImIiOiAyNTUsCiAgICAgICAgInBpeGVsQ291bnRUaHJlc2hvbGQiOiA1MAogICAgfV0sCiAgICAibWFza0RldGFpbHMiOiB7CiAgICAgICAgInhjb3JkIjogMTQ2OCwKICAgICAgICAieWNvcmQiOiA1MjUsCiAgICAgICAgIndpZHRoIjogMTc1LAogICAgICAgICJoZWlnaHQiOiAxNjcKICAgIH0KfQ=="
#bufferng at centre
time.sleep(540)
algorithm.Params = "eyAgICAicmdiRGV0YWlsc0xpc3QiOiBbewogICAgICAgICJyIjogMTAwLAogICAgICAgICJnIjogMzEsCiAgICAgICAgImIiOiAxNDAsCiAgICAgICAgInBpeGVsQ291bnRUaHJlc2hvbGQiOiA5MAogICAgfSwgewogICAgICAgICJyIjogMjU1LAogICAgICAgICJnIjogMTE2LAogICAgICAgICJiIjogNSwKICAgICAgICAicGl4ZWxDb3VudFRocmVzaG9sZCI6IDkwCiAgICB9LCB7CiAgICAgICAgInIiOiA0MSwKICAgICAgICAiZyI6IDEzOSwKICAgICAgICAiYiI6IDI2LAogICAgICAgICJwaXhlbENvdW50VGhyZXNob2xkIjogOTAKICAgIH0sIHsKICAgICAgICAiciI6IDAsCiAgICAgICAgImciOiAxMDEsCiAgICAgICAgImIiOiAyNTUsCiAgICAgICAgInBpeGVsQ291bnRUaHJlc2hvbGQiOiA5MAogICAgfV0sCiAgICAibWFza0RldGFpbHMiOiB7CiAgICAgICAgInhjb3JkIjogOTE2LAogICAgICAgICJ5Y29yZCI6IDQ5OCwKICAgICAgICAid2lkdGgiOiA5MCwKICAgICAgICAiaGVpZ2h0IjogODcKICAgIH0KfQ=="
algorithmList.Add(algorithm) 
request.Duration = 50
request.Token = reservationResponse.Data.Token
request.Algorithms = algorithmList 
request.DeviceInfo = deviceInfo 
response = dut.validator.StartHighPrecisionFrameAnalysis(request) 


#if reservationResponse.Data.Token == '':
#    pass
#else:
#    dut.controller.sendCommand("Home") 
#    time.sleep(2) 
#    dut.controller.sendCommand("Down") 
#    time.sleep(2) 
#    dut.controller.sendCommand("Ok") 
#    time.sleep(5) 
#    dut.controller.sendCommand("Ok") 
#    time.sleep(15)
#    dut.controller.sendCommand("Right") 
#    time.sleep(2) 
#    dut.controller.sendCommand("Right") 
#    time.sleep(2) 
#    dut.controller.sendCommand("Ok") 
#    time.sleep(15)
#    
#    statusRequest = ScriptingLibrary.HighPrecisionValidationService.VideoAnalysisStatusRequest() 
#    statusRequest.Token = response.Data.Token 
#    statusResponse = dut.validator.GetHighPrecisionFrameAnalysisResult(statusRequest) 
#    
#    sum_of_duration = 0
#    while statusResponse.Status == 'In Progress':
#        logger.Log("'In Progress', so sleepingggggggggggg")
#        time.sleep(5)
#        statusResponse = dut.validator.GetHighPrecisionFrameAnalysisResult(statusRequest)
#    statusResponse = dut.validator.GetHighPrecisionFrameAnalysisResult(statusRequest)
#    if statusResponse is not None and statusResponse.Data is not None:
#        for data in statusResponse.Data:
#            for algorithm_data in data.AlgorithmData:
#                logger.Log("Duration obtained from API >>> " + str(algorithm_data.Duration))
#                dut.CommitStepResult("Duration Obtained!", str(algorithm_data.Duration))
#                sum_of_duration += algorithm_data.Duration
#    else:
#        logger.Log("Failed to get duration")
