# ''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
# TestCase ID:
# Description:
# Author:
# Date:
# Version:

# ''''''''''''''''''''AUTOGENERATED CODE - DO NOT MODIFY''''''''''''''''''''
import clr
import sys
import os
import time
clr.AddReference("MobileScriptingLibrary")
import MobileScriptingLibrary
dut = MobileScriptingLibrary.MobileDUT()
logger = MobileScriptingLibrary.Logger()
chkpt = MobileScriptingLibrary.CheckPoint()
config = MobileScriptingLibrary.DeviceConfig()

# ''''''''''''''''''''''''''''''''IMPORTS'''''''''''''''''''''''''''''''''''
# ''''''''''''''''''''''''''''''END IMPORTS'''''''''''''''''''''''''''''''''

# ''''''''''''''''''''''''''''''FOR iOS DEVICE''''''''''''''''''''''''''''''
config.DeviceType = "iOS"
config.AppName = "com.google.ios.youtube"


args = sys.argv
scriptPath = os.path.realpath(__file__)
dut.Configure(args[1], args[2], args[3], args[4], scriptPath)
logger.Configure(args[1], args[2], args[3], args[4], scriptPath)

for i in range(1000000):
    if (dut.InitApp(config)):
        logger.Log("Image capture " + str(i))
        dut.validator.CaptureImage(
            11, 34, 113, 62, "ImageName" + str(i), 98, 2)
        time.sleep(2)
        dut.validator.QuickCapture("test" + str(i))
        dut.CloseApp()
        dut.Stop()
    else:
        dut.CommitStepResult("InitApp", "FAILED")

# '''''''''''''''''''''''''END AUTOGENERATED CODE'''''''''''''''''''''''''''
# ''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
