# ''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
# TestCase ID:
# Description:
# Author:
# Date:
# Version:

# ''''''''''''''''''''AUTOGENERATED CODE - DO NOT MODIFY''''''''''''''''''''
import clr
import sys
import os
import time
clr.AddReference("MobileScriptingLibrary")
import MobileScriptingLibrary
dut = MobileScriptingLibrary.MobileDUT()
logger = MobileScriptingLibrary.Logger()
chkpt = MobileScriptingLibrary.CheckPoint()
config = MobileScriptingLibrary.DeviceConfig()

# ''''''''''''''''''''''''''''''''IMPORTS'''''''''''''''''''''''''''''''''''
# ''''''''''''''''''''''''''''''END IMPORTS'''''''''''''''''''''''''''''''''

# ''''''''''''''''''''''''''''''FOR iOS DEVICE''''''''''''''''''''''''''''''
# config.DeviceType = "iOS"
# config.AppName = "com.google.ios.youtube"


# ''''''''''''''''''''''''''''FOR ANDROID DEVICE''''''''''''''''''''''''''''
config.DeviceType = "Android"
config.AppPackage = "com.google.android.youtube"
config.AppActivity = ".HomeActivity"

args = sys.argv
scriptPath = os.path.realpath(__file__)
dut.Configure(args[1], args[2], args[3], args[4], scriptPath)
logger.Configure(args[1], args[2], args[3], args[4], scriptPath)

for i in range(10000000):
    if (dut.InitApp(config)):			
        logger.Log("Image capture " + str(i))
        dut.validator.CaptureImage(
            11, 34, 113, 62, "ImageName" + str(i), 98, 2)
        time.sleep(2)
        dut.validator.QuickCapture("test" + str(i))
        if(dut.Click(MobileScriptingLibrary.Constants.ElementType.ClassName, "android.widget.ImageView", 2)):
            dut.CommitStepResult("Click on Search", "PASSED")
            time.sleep(3)
            dut.SendKeys(
                MobileScriptingLibrary.Constants.ElementType.Id,
                "com.google.android.youtube:id/search_edit_text",
                "MasterChef Australia")
            time.sleep(3)
            dut.SendAndroidKeyCode("Keycode_ENTER")
            time.sleep(3)
            dut.Tap(241, 370)
            dut.validator.CaptureImage(
                11, 34, 113, 62, "ImageName1" + str(i), 98, 2)
            time.sleep(2)
            dut.validator.QuickCapture("test1" + str(i))
        else:
            dut.CommitStepResult("Click on Search", "FAILED")
            dut.CloseApp()
            dut.Stop()
    else:
        dut.CommitStepResult("InitApp", "FAILED")

# '''''''''''''''''''''''''END AUTOGENERATED CODE'''''''''''''''''''''''''''
# ''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
