#''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
# TestCase ID:
# Description:
# Author:
# Date:
# Version:
#''''''''''''''''''''AUTOGENERATED CODE - DO NOT MODIFY''''''''''''''''''''
import clr
import sys
import os
import time
from System.Collections.Generic import List
clr.AddReference("ScriptingLibrary")
import ScriptingLibrary
dut = ScriptingLibrary.DUT()
logger = ScriptingLibrary.Logger()
chkpt = ScriptingLibrary.CheckPoint()
testResult = ScriptingLibrary.TestResult()
args = sys.argv
scriptPath = os.path.realpath(__file__)
remoteFiringType = "IP"
dut.Configure(args[1], args[2], args[3], args[4], scriptPath, remoteFiringType)
logger.Configure(args[1], args[2], args[3], args[4], scriptPath)

# ''''''''''''''''''''''''''''''''IMPORTS''''''''''''''''''''''''''''''''''
# ''''''''''''''''''''''''''''''END IMPORTS''''''''''''''''''''''''''''''''

#'''''''''''''''''''''''''END AUTOGENERATED CODE'''''''''''''''''''''''''''
# ''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
#key = "Exit"

dut.controller.sendCommand("Back")
time.sleep(5)
dut.controller.sendCommand("Back")


resp = ScriptingLibrary.APIResponse.ResponseData()
inputParam1 = ScriptingLibrary.HighPrecisionValidationService.MotionParams()
inputParam1.x_cord = 159#498
inputParam1.y_cord = 293#303
inputParam1.width = 537#289
inputParam1.height = 380#98
inputParam1.sensitivity = 3
lstInputParam = List[ScriptingLibrary.HighPrecisionValidationService.MotionParams]()
inputParam1.enableAggrassiveMode = True
lstInputParam.Add(inputParam1)
dut.controller.cacheCommand("Home")
inputParam2 = ScriptingLibrary.HighPrecisionValidationService.MotionParams()
inputParam2.x_cord = 847#113
inputParam2.y_cord =265#65
inputParam2.width = 832#1368
inputParam2.height = 603#782
inputParam2.sensitivity = 3
inputParam2.enableAggressiveMode = True
lstInputParam.Add(inputParam2)
inputParam3 = ScriptingLibrary.HighPrecisionValidationService.MotionParams()
inputParam3.x_cord = 847#113
inputParam3.y_cord =265#65
inputParam3.width = 832#1368
inputParam3.height = 603#782
inputParam3.sensitivity = 3
inputParam3.enableAggressiveMode = True
lstInputParam.Add(inputParam3)
inputParam4 = ScriptingLibrary.HighPrecisionValidationService.MotionParams()
inputParam4.x_cord = 847#113
inputParam4.y_cord =265#65
inputParam4.width = 832#1368
inputParam4.height = 603#782
inputParam4.sensitivity = 3
inputParam4.enableAggressiveMode = True
lstInputParam.Add(inputParam4)
inputParam5 = ScriptingLibrary.HighPrecisionValidationService.MotionParams()
inputParam5.x_cord = 847#113
inputParam5.y_cord =265#65
inputParam5.width = 832#1368
inputParam5.height = 603#782
inputParam5.sensitivity = 3
inputParam5.enableAggressiveMode = True
lstInputParam.Add(inputParam5)
inputParam6 = ScriptingLibrary.HighPrecisionValidationService.MotionParams()
inputParam6.x_cord = 847#113
inputParam6.y_cord =265#65
inputParam6.width = 832#1368
inputParam6.height = 603#782
inputParam6.sensitivity = 10
inputParam6.enableAggressiveMode = True
lstInputParam.Add(inputParam6)
inputParam7 = ScriptingLibrary.HighPrecisionValidationService.MotionParams()
inputParam7.x_cord = 847#113
inputParam7.y_cord =265#65
inputParam7.width = 832#1368
inputParam7.height = 603#782
inputParam7.sensitivity = 10
inputParam7.enableAggressiveMode = True
lstInputParam.Add(inputParam7)

stepcommit = "valid arguments"
expected = "Screen transition obtained"

resp = dut.validator.DetectScreenChange(120, lstInputParam)
logger.Log (str(resp.MotionData[0].Duration)) 
logger.Log (str(resp.MotionData[1].Duration))
logger.Log (str(resp.MotionData[2].Duration)) 
logger.Log (str(resp.MotionData[3].Duration))
logger.Log (str(resp.MotionData[4].Duration))
logger.Log (str(resp.MotionData[5].Duration))
logger.Log (str(resp.MotionData[6].Duration))

