# ''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
# TestCase ID: HOughCircle_BufferingAPI
# Description:
# Author: Smasung_21435,Samsung_a445_Voot App and video freeze
# Date:
# Version:

# ''''''''''''''''''''AUTOGENERATED CODE - DO NOT MODIFY''''''''''''''''''''
import clr
import sys
import os
import time
import base64
from System.Collections.Generic import List
clr.AddReference("MobileScriptingLibrary")
import MobileScriptingLibrary
dut = MobileScriptingLibrary.MobileDUT()
logger = MobileScriptingLibrary.Logger()
chkpt = MobileScriptingLibrary.CheckPoint()
config = MobileScriptingLibrary.DeviceConfig()

# ''''''''''''''''''''''''''''''''IMPORTS'''''''''''''''''''''''''''''''''''
# ''''''''''''''''''''''''''''''END IMPORTS'''''''''''''''''''''''''''''''''

# ''''''''''''''''''''''''''''''FOR iOS DEVICE''''''''''''''''''''''''''''''
#config.DeviceType = "iOS"
#config.AppName = "com.google.ios.youtube"
# config.AppName = "in.startv.hotstar" #ios


# ''''''''''''''''''''''''''''FOR ANDROID DEVICE''''''''''''''''''''''''''''
# config.DeviceType = "Android"
# config.AppPackage = "com.bskyb.nowtv.beta"
# config.AppActivity = "com.nowtv.view.activity.StartupActivity"

# config.DeviceType = "Android"
# config.AppPackage = "com.bskyb.skygo"
# config.AppActivity = "com.bskyb.uma.app.bootstrap.BootstrapActivity"

config.DeviceType = "Android"
config.AppPackage = "com.tv.v18.viola"
config.AppActivity = "com.tv.v18.viola.views.activities.RSHomeActivity"

# config.DeviceType = "Android"
# config.AppPackage = "com.google.android.youtube"
# config.AppActivity = ".HomeActivity"

args = sys.argv
scriptPath = os.path.realpath(__file__)
dut.Configure(args[1], args[2], args[3], args[4], scriptPath)
logger.Configure(args[1], args[2], args[3], args[4], scriptPath)

buffering_check_completed = False
interval = 120
istarttime = time.time()
iendtime = time.time()
#while not (iendtime - istarttime) > interval:
#    iendtime = time.time()

try:
    if(dut.InitApp(config)):
        time.sleep(30)
        dut.Tap(551, 1906)  # for Skip and continue for Smasung 21435
        time.sleep(10)
        dut.Tap(534, 1156)
        time.sleep(1)
        dut.Tap(353, 731)
        time.sleep(40)
        logger.Log("App launched.")
        # dut.TapElement(ElementType,"Element Id",index)
        reservationRequest = MobileScriptingLibrary.HighPrecisionValidationService.SlotReservationRequest()
        reservationRequest.AlgorithmCount = 1
        reservationResponse = dut.ReserveSlotForHPA(reservationRequest)
        logger.Log("Response - " + reservationResponse.Data.Token)
        if(reservationResponse.Status):
            request = MobileScriptingLibrary.HighPrecisionValidationService.VideoAnalysisRequest()

            deviceInfo = MobileScriptingLibrary.HighPrecisionValidationService.DeviceInfo()
            algorithmList = List[MobileScriptingLibrary.HighPrecisionValidationService.Algorithm](
            )
            algorithm = MobileScriptingLibrary.HighPrecisionValidationService.Algorithm()
            # algorithm.Name = "Histogram"
            # algorithm.Params = "eyAgICAicmdiRGV0YWlsc0xpc3QiOiBbewogICAgICAgICJyIjogMTAwLAogICAgICAgICJnIjogMzEsCiAgICAgICAgImIiOiAxNDAsCiAgICAgICAgInBpeGVsQ291bnRUaHJlc2hvbGQiOiA4MAogICAgfSwgewogICAgICAgICJyIjogMjU1LAogICAgICAgICJnIjogMTE2LAogICAgICAgICJiIjogNSwKICAgICAgICAicGl4ZWxDb3VudFRocmVzaG9sZCI6IDgwCiAgICB9LCB7CiAgICAgICAgInIiOiA0MSwKICAgICAgICAiZyI6IDEzOSwKICAgICAgICAiYiI6IDI2LAogICAgICAgICJwaXhlbENvdW50VGhyZXNob2xkIjogODAKICAgIH0sIHsKICAgICAgICAiciI6IDAsCiAgICAgICAgImciOiAxMDEsCiAgICAgICAgImIiOiAyNTUsCiAgICAgICAgInBpeGVsQ291bnRUaHJlc2hvbGQiOiA4MAogICAgfV0sCiAgICAibWFza0RldGFpbHMiOiB7CiAgICAgICAgInhjb3JkIjogNTkxLAogICAgICAgICJ5Y29yZCI6IDMxMywKICAgICAgICAid2lkdGgiOiA5OCwKICAgICAgICAiaGVpZ2h0IjogODkKICAgIH0KfQ=="
            # algorithmList.Add(algorithm)
            # Test WEorking JSOn
#                algorithm = MobileScriptingLibrary.HighPrecisionValidationService.Algorithm()
#                algorithm.Name = "HoughCircles"
#                algorithm.Params = "ewogICJtYXNrRGV0YWlscyI6IHsKICAgICJ4Y29yZCI6IDMyMiwKICAgICJ5Y29yZCI6IDIwMywKICAgICJ3aWR0aCI6IDc2LAogICAgImhlaWdodCI6IDkwCiAgfSwKICAiY2lyY2xlVGhyZXNob2xkcyI6IHsKICAgICJjaXJjbGVQZXJjZW50YWdlTG93TGltaXQiOiAzMCwKICAgICJjaXJjbGVQZXJjZW50YWdlVXBMaW1pdCI6IDg1LAogICAgImNpcmNsZVJhZGl1c0xvd0xpbWl0IjogMzAsCiAgICAiY2lyY2xlUmFkaXVzVXBMaW1pdCI6IDQwLAogICAgImNpcmNsZUNlbnRlclhPZmZzZXQiOiAxNSwKICAgICJjaXJjbGVDZW50ZXJZT2Zmc2V0IjogMTguMCwKICAgICJjaXJjbGVDZW50ZXJXaWR0aCI6IDMwLjAsCiAgICAiY2lyY2xlQ2VudGVySGVpZ2h0IjogMzAuMAogIH0sCiAgIm1pc2NUaHJlc2hvbGRzIjogewogICAgImNhbm55VGhyZXNob2xkMSI6IDM1LAogICAgImNhbm55VGhyZXNob2xkMiI6IDgwLAogICAgImhvdWdoRHAiOiAxLjQsCiAgICAiaG91Z2hNaW5EaXN0IjogNTAuMCwKICAgICJob3VnaFBhcmFtMSI6IDgwLjAsCiAgICAiaG91Z2hQYXJhbTIiOiAzNy4wLAogICAgImRpc3RUcmFuc2Zvcm1GaWx0ZXJEaXN0IjogMwogIH0KfQ=="
#                # if Change orientation in Landscape mode
#                #algorithm.Params= "ewogICJtYXNrRGV0YWlscyI6IHsKICAgICJ4Y29yZCI6IDU5MSwKICAgICJ5Y29yZCI6IDMxNCwKICAgICJ3aWR0aCI6IDk3LAogICAgImhlaWdodCI6IDkzCiAgfSwKICAiY2lyY2xlVGhyZXNob2xkcyI6IHsKICAgICJjaXJjbGVQZXJjZW50YWdlTG93TGltaXQiOiAzMCwKICAgICJjaXJjbGVQZXJjZW50YWdlVXBMaW1pdCI6IDg1LAogICAgImNpcmNsZVJhZGl1c0xvd0xpbWl0IjogMzAsCiAgICAiY2lyY2xlUmFkaXVzVXBMaW1pdCI6IDQwLAogICAgImNpcmNsZUNlbnRlclhPZmZzZXQiOiAxNSwKICAgICJjaXJjbGVDZW50ZXJZT2Zmc2V0IjogMTguMCwKICAgICJjaXJjbGVDZW50ZXJXaWR0aCI6IDMwLjAsCiAgICAiY2lyY2xlQ2VudGVySGVpZ2h0IjogMzAuMAogIH0sCiAgIm1pc2NUaHJlc2hvbGRzIjogewogICAgImNhbm55VGhyZXNob2xkMSI6IDM1LAogICAgImNhbm55VGhyZXNob2xkMiI6IDgwLAogICAgImhvdWdoRHAiOiAxLjQsCiAgICAiaG91Z2hNaW5EaXN0IjogNTAuMCwKICAgICJob3VnaFBhcmFtMSI6IDgwLjAsCiAgICAiaG91Z2hQYXJhbTIiOiAzNy4wLAogICAgImRpc3RUcmFuc2Zvcm1GaWx0ZXJEaXN0IjogMwogIH0KfQ=="
#                algorithmList.Add(algorithm)
            #################################
            # Voot app Json working
            algorithm = MobileScriptingLibrary.HighPrecisionValidationService.Algorithm()
            algorithm.Name = "HoughCircles"
            algorithm.Params ="ewogICJtYXNrRGV0YWlscyI6IHsKICAgICJ4Y29yZCI6IDMyMiwKICAgICJ5Y29yZCI6IDIwMywKICAgICJ3aWR0aCI6IDc2LAogICAgImhlaWdodCI6IDkwCiAgfSwKICAiY2lyY2xlVGhyZXNob2xkcyI6IHsKICAgICJjaXJjbGVQZXJjZW50YWdlTG93TGltaXQiOiAzMCwKICAgICJjaXJjbGVQZXJjZW50YWdlVXBMaW1pdCI6IDg1LAogICAgImNpcmNsZVJhZGl1c0xvd0xpbWl0IjogMzAsCiAgICAiY2lyY2xlUmFkaXVzVXBMaW1pdCI6IDQwLAogICAgImNpcmNsZUNlbnRlclhPZmZzZXQiOiAxNSwKICAgICJjaXJjbGVDZW50ZXJZT2Zmc2V0IjogMTguMCwKICAgICJjaXJjbGVDZW50ZXJXaWR0aCI6IDMwLjAsCiAgICAiY2lyY2xlQ2VudGVySGVpZ2h0IjogMzAuMAogIH0sCiAgIm1pc2NUaHJlc2hvbGRzIjogewogICAgImNhbm55VGhyZXNob2xkMSI6IDM1LAogICAgImNhbm55VGhyZXNob2xkMiI6IDgwLAogICAgImhvdWdoRHAiOiAxLjQsCiAgICAiaG91Z2hNaW5EaXN0IjogNTAuMCwKICAgICJob3VnaFBhcmFtMSI6IDgwLjAsCiAgICAiaG91Z2hQYXJhbTIiOiAzNy4wLAogICAgImRpc3RUcmFuc2Zvcm1GaWx0ZXJEaXN0IjogMwogIH0KfQ=="
            #algorithm.Params = "ewoJIm1hc2tEZXRhaWxzIjogewoJCSJ4Y29yZCI6IDI4NiwKCQkieWNvcmQiOiAxNzQsCgkJIndpZHRoIjogMTUwLAoJCSJoZWlnaHQiOiAxNTIKCX0sCgkiY2lyY2xlVGhyZXNob2xkcyI6IHsKCQkiY2lyY2xlUGVyY2VudGFnZUxvd0xpbWl0IjogMzEsCgkJImNpcmNsZVBlcmNlbnRhZ2VVcExpbWl0IjogODYsCgkJImNpcmNsZVJhZGl1c0xvd0xpbWl0IjogNzAsCgkJImNpcmNsZVJhZGl1c1VwTGltaXQiOiA3OCwKCQkiY2lyY2xlQ2VudGVyWE9mZnNldCI6IDMyLAoJCSJjaXJjbGVDZW50ZXJZT2Zmc2V0IjogMzIsCgkJImNpcmNsZUNlbnRlcldpZHRoIjogNzAsCgkJImNpcmNsZUNlbnRlckhlaWdodCI6IDcwCgl9LAoJIm1pc2NUaHJlc2hvbGRzIjogewoJCSJjYW5ueVRocmVzaG9sZDEiOiAzNSwKCQkiY2FubnlUaHJlc2hvbGQyIjogODAsCgkJImhvdWdoRHAiOiAxLjQsCgkJImhvdWdoTWluRGlzdCI6IDUwLjAsCgkJImhvdWdoUGFyYW0xIjogODAuMCwKCQkiaG91Z2hQYXJhbTIiOiAzNy4wLAoJCSJkaXN0VHJhbnNmb3JtRmlsdGVyRGlzdCI6IDMKCX0KfQ=="
            algorithmList.Add(algorithm)
            # Video Freeze for Voot APP
#            algorithm = MobileScriptingLibrary.HighPrecisionValidationService.Algorithm()
#            algorithm.Name = "VideoFreeze"
#            algorithm.IsReferenceBased = True
## co orinates overlap houghcircles
## algorithm.Params = "ewoJIk1hdGNoU2NvcmUiOiAwLjk5LAoJIk1hc2tEZXRhaWxzIjogewoJCSJ4Y29yZCI6IDIwMCwKCQkieWNvcmQiOiAxMjUsCgkJIndpZHRoIjogMzI4LAoJCSJoZWlnaHQiOjI0NSAKCX0KfQ=="
## co orinates outside houghcircles
##                # algorithm.Params="ewoJIk1hdGNoU2NvcmUiOiAwLjk5LAoJIk1hc2tEZXRhaWxzIjogewoJCSJ4Y29yZCI6IDM5LAoJCSJ5Y29yZCI6IDY2LAoJCSJ3aWR0aCI6IDI2MiwKCQkiaGVpZ2h0IjoyNjkgCgl9Cn0="
#            json_input = {
#                    "MatchScore": 0.99,
#                    "MaskDetails":{
#                    "xcord": 39,
#                    "ycord": 66,
#                    "width": 262,
#                    "height": 269}  
#            }
#            # out side coordinates  from Hough Circles 39,66,262,269  and
#            # include match temp 139 105 453 246
#            base64input = base64.b64encode(bytes(json_input), 'utf-8')
#            algorithm.Params = base64input
#            algorithm.MinDuration = 1000
#            algorithm.MinTimeGap = 1000
#            algorithmList.Add(algorithm)
            # Checking after Video Freeze
#                algorithm = MobileScriptingLibrary.HighPrecisionValidationService.Algorithm()
#                algorithm.Name = "HoughCircles"
#                algorithm.Params = "ewogICJtYXNrRGV0YWlscyI6IHsKICAgICJ4Y29yZCI6IDMyMiwKICAgICJ5Y29yZCI6IDIwMywKICAgICJ3aWR0aCI6IDc2LAogICAgImhlaWdodCI6IDkwCiAgfSwKICAiY2lyY2xlVGhyZXNob2xkcyI6IHsKICAgICJjaXJjbGVQZXJjZW50YWdlTG93TGltaXQiOiAzMCwKICAgICJjaXJjbGVQZXJjZW50YWdlVXBMaW1pdCI6IDg1LAogICAgImNpcmNsZVJhZGl1c0xvd0xpbWl0IjogMzAsCiAgICAiY2lyY2xlUmFkaXVzVXBMaW1pdCI6IDQwLAogICAgImNpcmNsZUNlbnRlclhPZmZzZXQiOiAxNSwKICAgICJjaXJjbGVDZW50ZXJZT2Zmc2V0IjogMTguMCwKICAgICJjaXJjbGVDZW50ZXJXaWR0aCI6IDMwLjAsCiAgICAiY2lyY2xlQ2VudGVySGVpZ2h0IjogMzAuMAogIH0sCiAgIm1pc2NUaHJlc2hvbGRzIjogewogICAgImNhbm55VGhyZXNob2xkMSI6IDM1LAogICAgImNhbm55VGhyZXNob2xkMiI6IDgwLAogICAgImhvdWdoRHAiOiAxLjQsCiAgICAiaG91Z2hNaW5EaXN0IjogNTAuMCwKICAgICJob3VnaFBhcmFtMSI6IDgwLjAsCiAgICAiaG91Z2hQYXJhbTIiOiAzNy4wLAogICAgImRpc3RUcmFuc2Zvcm1GaWx0ZXJEaXN0IjogMwogIH0KfQ=="
#                # if Change orientation in Landscape mode
#                #algorithm.Params= "ewogICJtYXNrRGV0YWlscyI6IHsKICAgICJ4Y29yZCI6IDU5MSwKICAgICJ5Y29yZCI6IDMxNCwKICAgICJ3aWR0aCI6IDk3LAogICAgImhlaWdodCI6IDkzCiAgfSwKICAiY2lyY2xlVGhyZXNob2xkcyI6IHsKICAgICJjaXJjbGVQZXJjZW50YWdlTG93TGltaXQiOiAzMCwKICAgICJjaXJjbGVQZXJjZW50YWdlVXBMaW1pdCI6IDg1LAogICAgImNpcmNsZVJhZGl1c0xvd0xpbWl0IjogMzAsCiAgICAiY2lyY2xlUmFkaXVzVXBMaW1pdCI6IDQwLAogICAgImNpcmNsZUNlbnRlclhPZmZzZXQiOiAxNSwKICAgICJjaXJjbGVDZW50ZXJZT2Zmc2V0IjogMTguMCwKICAgICJjaXJjbGVDZW50ZXJXaWR0aCI6IDMwLjAsCiAgICAiY2lyY2xlQ2VudGVySGVpZ2h0IjogMzAuMAogIH0sCiAgIm1pc2NUaHJlc2hvbGRzIjogewogICAgImNhbm55VGhyZXNob2xkMSI6IDM1LAogICAgImNhbm55VGhyZXNob2xkMiI6IDgwLAogICAgImhvdWdoRHAiOiAxLjQsCiAgICAiaG91Z2hNaW5EaXN0IjogNTAuMCwKICAgICJob3VnaFBhcmFtMSI6IDgwLjAsCiAgICAiaG91Z2hQYXJhbTIiOiAzNy4wLAogICAgImRpc3RUcmFuc2Zvcm1GaWx0ZXJEaXN0IjogMwogIH0KfQ=="
#                algorithmList.Add(algorithm)
            request.Duration = 200
            request.Token = reservationResponse.Data.Token
            request.Algorithms = algorithmList
            request.DeviceInfo = deviceInfo
            logger.Log(" Starting Execution for StartHighPrecisionFrameAnalysis")
            response = dut.validator.StartHighPrecisionFrameAnalysis(
                request)
            time.sleep(2)
            #logger.Log("Response - " + response.Data)
            # time.sleep(30)
            # dut.Tap(265,721)   #Android   NowTv
            # dut.Tap(366,1109)
            #dut.Tap(556, 830)
#                dut.Tap(534, 556)  # Voot on Android if kid page not available
#                time.sleep(1)
#                dut.Tap(371, 590)  # Voot on Android
            dut.Tap(589, 1334)
            time.sleep(10)
#                chkpt.init("Voot_HoughCircle")#("500_OCR")
#                if(dut.validator.validateCheckPoint((chkpt))):
#                    #logger.Log("Required Screen reached")
#                    dut.CommitTestResult("PASSED")
#                else:
#                    #logger.Error("Wrong Screen reached")
#                    dut.CommitTestResult("FAILED")
            #dut.ChangeOrientation()
            #logger.Log("Response - " + str(response.Data))
            #logger.Log("Response Token- " + response.Data.Token)
            #if response.Data.Status == 'Failed':
            statusRequest = MobileScriptingLibrary.HighPrecisionValidationService.VideoAnalysisStatusRequest()
            # time.sleep(10)
            statusRequest.Token = response.Data.Token
            statusResponse = dut.validator.GetHighPrecisionFrameAnalysisResult(statusRequest)
            logger.Log("Status of GetHighPrecisionFrameAnalysisResult response "+str(statusResponse.Status))

            while statusResponse.Status == 'In Progress':
                logger.Log("'In Progress', Continues....")
                time.sleep(2)
                statusResponse = dut.validator.GetHighPrecisionFrameAnalysisResult(statusRequest)
                # dut.validator.StopHighPrecisionFrameAnalysis(response.Data.Token)
                #logger.Log("StatusResponse - " + str(statusResponse))
#                if statusResponse.Status == 'Failed':
#                    logger.Log("StatusResponse -  Failed") 
#                    break
#                else:
                if statusResponse is not None and statusResponse.Data is not None and statusResponse.Data.Count > 0 and statusResponse.Status == 'Completed':
                    sum_duration=0
                    for data in statusResponse.Data:
                        for algorithm_data in data.AlgorithmData:
                            logger.Log("Duration  returned by API -" + str(algorithm_data.Duration))
                            sum_duration += algorithm_data.Duration
                else:
                    logger.Log("Failed to get duration")
            logger.Log("Total duration =========> "+str(sum_duration))    
finally:
    #pass
    # dut.validator.StopAllHighPrecisionFrameAnalysis()
    dut.CloseApp()

# '''''''''''''''''''''''''END AUTOGENERATED CODE'''''''''''''''''''''''''''
# ''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
