#'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''' 
#TestCase ID: 
#Description: 
#Author: 
#Date: 
#Version: 

#''''''''''''''''''''AUTOGENERATED CODE - DO NOT MODIFY'''''''''''''''''''' 
import clr,sys,os,time 
import timeit
from datetime import datetime, timedelta
clr.AddReference("MobileScriptingLibrary") 
import MobileScriptingLibrary 
dut = MobileScriptingLibrary.MobileDUT() 
logger = MobileScriptingLibrary.Logger() 
chkpt = MobileScriptingLibrary.CheckPoint() 
config = MobileScriptingLibrary.DeviceConfig() 

#''''''''''''''''''''''''''''''''IMPORTS''''''''''''''''''''''''''''''''''' 
#''''''''''''''''''''''''''''''END IMPORTS''''''''''''''''''''''''''''''''' 

#''''''''''''''''''''''''''''''FOR iOS DEVICE'''''''''''''''''''''''''''''' 
#config.DeviceType = "iOS" 
#config.AppName = "com.google.ios.youtube" 


#''''''''''''''''''''''''''''FOR ANDROID DEVICE'''''''''''''''''''''''''''' 
config.DeviceType = "Android" 
config.AppPackage = "com.google.android.youtube" 
config.AppActivity = ".HomeActivity" 
config.CreateNewServer = "true"

args = sys.argv 
scriptPath = os.path.realpath(__file__) 
dut.Configure(args[1],args[2],args[3],args[4],scriptPath) 
logger.Configure(args[1],args[2],args[3],args[4],scriptPath) 
str_url_list = ["21435","slot0","aa445","STB"]
d = datetime.now()
t_end =d+timedelta(hours=6)
while d < t_end:
    for i in str_url_list:
        dut.InitApp(config)
        time.sleep(5)
        imageName="Test"  
        imageformat ="BMP"
        test=dut.validator.SetActiveFrameSource("21435")
        imagePath =dut.validator.QuickCaptureEx(imageName,imageformat)
        time.sleep(5)
        test=dut.validator.SetActiveFrameSource("slot0")
        imagePath =dut.validator.QuickCaptureEx(imageName,imageformat)
        test=dut.validator.SetActiveFrameSource("aa445")
        imagePath = dut.validator.QuickCaptureEx(imageName,imageformat)
        dut.Stop()
    d = datetime.now()    


#try: 
    #if(dut.InitApp(config)): 
        #logger.Log("App launched.")
        #time.sleep(20)
        #imagePath = dut.validator.QuickCapture("Test1")
        #dut.Tap(500,500)
#
#finally: 
    ##dut.Stop() 
    #time.sleep(2)

#'''''''''''''''''''''''''END AUTOGENERATED CODE''''''''''''''''''''''''''' 
#''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''



#dut.GetText(MobileScriptingLibrary.Constants.ElementType.XPath, "//android.widget.ImageView[@content-desc='Search']", 0)
## dut.InitApp(config)
## time.sleep(30)
#start_time = datetime.now()
#dut.GetDeviceWidth()
#end_time=datetime.now()
#print('Duration1: {}'.format(end_time - start_time))
#start_time = datetime.now()
#dut.GetDeviceHeight()
#end_time=datetime.now()
#print('Duration2: {}'.format(end_time - start_time))
#start_time = datetime.now()
#dut.GetWidth(MobileScriptingLibrary.Constants.ElementType.XPath, "//XCUIElementTypeImage[@name='youtube_logo']")
#end_time=datetime.now()
#print('Duration3: {}'.format(end_time - start_time))
#start_time = datetime.now()
#dut.GetHeight(MobileScriptingLibrary.Constants.ElementType.XPath, "//XCUIElementTypeImage[@name='youtube_logo']")
#end_time=datetime.now()
#print('Duration4: {}'.format(end_time - start_time))