#''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
#TestCase ID    :   M_API_03
#Description    :   QuickCapture functionality
#Author         :   Arathy P S
#Date           :   26-02-2018
#Version        :   0.0.1

#''''''''''''''''''''AUTOGENERATED CODE - DO NOT MODIFY''''''''''''''''''''
import clr
import sys
import os
import time
from datetime import datetime
clr.AddReference("MobileScriptingLibrary")
import MobileScriptingLibrary
dut = MobileScriptingLibrary.MobileDUT()
logger = MobileScriptingLibrary.Logger()
scriptPath = os.path.realpath(__file__)

#'''''''''''''''''''''''configure '''''''''''''''''''''''''''''''''''''''''
args = sys.argv
dut.Configure(args[1], args[2], args[3], args[4], scriptPath)
logger.Configure(args[1], args[2], args[3], args[4], scriptPath)
chkpt = MobileScriptingLibrary.CheckPoint()
config = MobileScriptingLibrary.DeviceConfig()
config.DeviceType = "Android"

config.AppPackage = "com.google.android.youtube"
config.AppActivity = "com.google.android.youtube.HomeActivity"
config.CreateNewServer= "true"
#'''''''''''''''''''''''''END AUTOGENERATED CODE'''''''''''''''''''''''''''
#''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''


chkpt.init("Image_SanityIos")
if(dut.validator.validateCheckPoint((chkpt))):
    "Passed"
else:
    "Failed"
imageName= "refImage"
imageformat ="213144"
str_url_list = ["Redmi","Camera1","21435","STB"]
if (dut.InitApp(config)):
    for i in str_url_list:
        #start_time = datetime.now()
        #print start_time
        test=dut.validator.SetActiveFrameSource(i)
        name = dut.validator.QuickCaptureEx(imageName,imageformat)
        #imagePath =dut.validator.QuickCapture(imageName)
        #end_time=datetime.now()
        #Duration=end_time - start_time
        #print('Duration2: {}'.format(end_time - start_time))
        #logger.Log("image name :" +str(name))
        #dut.CommitStepResult("Time",str(Duration))
    dut.CloseApp()
    dut.Stop()