#''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
#TestCase ID:
#Description:
#Author:
#Date:
#Version:

#''''''''''''''''''''AUTOGENERATED CODE - DO NOT MODIFY''''''''''''''''''''
import clr,sys,os,time
clr.AddReference("ScriptingLibrary")
import ScriptingLibrary
dut = ScriptingLibrary.DUT()
logger = ScriptingLibrary.Logger()
chkpt = ScriptingLibrary.CheckPoint()
testResult = ScriptingLibrary.TestResult()
args = sys.argv
scriptPath = os.path.realpath(__file__)
remoteFiringType = "IR"
dut.Configure(args[1],args[2],args[3],args[4],scriptPath,remoteFiringType)
logger.Configure(args[1],args[2],args[3],args[4],scriptPath)

#''''''''''''''''''''''''''''''''IMPORTS''''''''''''''''''''''''''''''''''
#''''''''''''''''''''''''''''''END IMPORTS''''''''''''''''''''''''''''''''

#'''''''''''''''''''''''''END AUTOGENERATED CODE'''''''''''''''''''''''''''
#''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''

##*********To check 'SELECT' key****************##
dut.controller.sendCommand("OK")
time.sleep(2)

##*********To check 'A' (ACCEPT) key************##
dut.controller.sendCommand("A")
time.sleep(60)

##*********To check 'PLAYPAUSE' key*************##
dut.controller.sendCommand("PlayPause")
time.sleep(2)
dut.controller.sendCommand("PlayPause")
time.sleep(60)

##*********To check 'FASTFORWARD' key************##
dut.controller.sendCommand("FastForward")
time.sleep(2)
dut.controller.sendCommand("PlayPause")
time.sleep(60)

##*********To check 'REWIND' key************##
dut.controller.sendCommand("Rewind")
time.sleep(2)
dut.controller.sendCommand("PlayPause")
time.sleep(60)

##*********To check 'FASTFORWARD' key************##
dut.controller.sendCommand("FastForward")
dut.controller.sendCommand("FastForward")
time.sleep(2)
dut.controller.sendCommand("PlayPause")
time.sleep(60)

##*********To check 'REWIND' key************##
dut.controller.sendCommand("Rewind")
dut.controller.sendCommand("Rewind")
time.sleep(2)
dut.controller.sendCommand("PlayPause")
time.sleep(60)

##*********To check 'SKIP+' key************##
dut.controller.sendCommand("Skip+")
time.sleep(60)

##*********To check 'SKIP-' key************##
dut.controller.sendCommand("Skip-")
time.sleep(60)

##*********To check 'B' (BACK) key************##
dut.controller.sendCommand("B")

##*********To check 'NAV_RIGHT' key************##
dut.controller.sendCommand("Right")
dut.controller.sendCommand("Right")

##*********To check 'NAV_LEFT' key************##
dut.controller.sendCommand("Left")
dut.controller.sendCommand("Left")

##*********To check 'Y' (SEARCH) key************##
dut.controller.sendCommand("Y")

##*********To check digits 0-9 keys************##
dut.controller.sendCommand("1")
dut.controller.sendCommand("2")
dut.controller.sendCommand("3")
dut.controller.sendCommand("4")
dut.controller.sendCommand("5")
dut.controller.sendCommand("6")
dut.controller.sendCommand("7")
dut.controller.sendCommand("8")
dut.controller.sendCommand("9")
dut.controller.sendCommand("0")

##*********To check 'X' (CLEAR/DELETE) key************##
dut.controller.sendCommand("X")
dut.controller.sendCommand("X")

##*********To check 'B' (BACK) key************##
dut.controller.sendCommand("B")
dut.controller.sendCommand("B")

##*********To check 'NAV_RIGHT' key************##
dut.controller.sendCommand("Right")
dut.controller.sendCommand("Right")
dut.controller.sendCommand("Right")


