#''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
#TestCase ID:
#Description:
#Author:
#Date:
#Version:

#''''''''''''''''''''AUTOGENERATED CODE - DO NOT MODIFY''''''''''''''''''''
import clr,sys,os,time
clr.AddReference("ScriptingLibrary")
import ScriptingLibrary
dut = ScriptingLibrary.DUT()
logger = ScriptingLibrary.Logger()
chkpt = ScriptingLibrary.CheckPoint()
testResult = ScriptingLibrary.TestResult()
args = sys.argv
scriptPath = os.path.realpath(__file__)
remoteFiringType = "IR"
dut.Configure(args[1],args[2],args[3],args[4],scriptPath,remoteFiringType)
logger.Configure(args[1],args[2],args[3],args[4],scriptPath)

#''''''''''''''''''''''''''''''''IMPORTS''''''''''''''''''''''''''''''''''
#''''''''''''''''''''''''''''''END IMPORTS''''''''''''''''''''''''''''''''

#'''''''''''''''''''''''''END AUTOGENERATED CODE'''''''''''''''''''''''''''
#''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''

def send_key(key, delay):
    dut.controller.sendCommand(key)
    time.sleep(delay)

send_key("Home", 3)


script_status = "PASSED"

send_key("Down", 1)
send_key("Down", 1)
send_key("Down", 1)
send_key("Home", 3)

chkpt.init("top_pick")
if(dut.validator.validateCheckPoint((chkpt))):
    dut.CommitStepResult("Checkpoint: top_pick","PASSED")
else:
    dut.CommitStepResult("Checkpoint: top_pick","FAILED")
    script_status = "FAILED"

send_key("Exit", 1)
send_key("Down", 1)
send_key("Down", 1)
send_key("Home", 1)
send_key("Down", 1)
send_key("Down", 1)
send_key("Exit", 1)

img = dut.validator.QuickCapture("exit_image")
logger.Log("Quickcapture path {}".format(img))

send_key("Home", 1)
send_key("Up", 1)
send_key("Up", 1)
send_key("Up", 1)
send_key("Up", 1)

img = dut.validator.QuickCapture("exit_image")
logger.Log("Quickcapture path {}".format(img))

send_key("Home", 1)

chkpt.init("top_pick")
if(dut.validator.validateCheckPoint((chkpt))):
    dut.CommitStepResult("Checkpoint: top_pick","PASSED")
else:
    dut.CommitStepResult("Checkpoint: top_pick","FAILED")
    script_status = "FAILED"

send_key("Up", 1)
send_key("Up", 1)
send_key("Up", 1)
send_key("Up", 1)

img = dut.validator.QuickCapture("exit_image")
logger.Log("Quickcapture path {}".format(img))

send_key("Down", 1)
send_key("Down", 1)
send_key("Home", 1)

dut.CommitTestResult(script_status)
