#''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
#TestCase ID:
#Description:
#Author:
#Date:
#Version:

#''''''''''''''''''''AUTOGENERATED CODE - DO NOT MODIFY''''''''''''''''''''
import clr,sys,os,time
clr.AddReference("ScriptingLibrary")
import ScriptingLibrary
dut = ScriptingLibrary.DUT()
logger = ScriptingLibrary.Logger()
chkpt = ScriptingLibrary.CheckPoint()
testResult = ScriptingLibrary.TestResult()
args = sys.argv
scriptPath = os.path.realpath(__file__)
remoteFiringType = "IR"
dut.Configure(args[1],args[2],args[3],args[4],scriptPath,remoteFiringType)
logger.Configure(args[1],args[2],args[3],args[4],scriptPath)

#''''''''''''''''''''''''''''''''IMPORTS''''''''''''''''''''''''''''''''''
#''''''''''''''''''''''''''''''END IMPORTS''''''''''''''''''''''''''''''''

#'''''''''''''''''''''''''END AUTOGENERATED CODE'''''''''''''''''''''''''''
#''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''

dut.controller.sendCommand("Home")

script_status = "PASSED"

dut.controller.sendCommand("Down")
dut.controller.sendCommand("Down")
dut.controller.sendCommand("Down")
dut.controller.sendCommand("Home")


chkpt.init("top_pick")
if(dut.validator.validateCheckPoint((chkpt))):
    dut.CommitStepResult("Checkpoint: top_pick","PASSED")
else:
    dut.CommitStepResult("Checkpoint: top_pick","FAILED")
    script_status = "FAILED"


dut.controller.sendCommand("Exit")
dut.controller.sendCommand("Down")
dut.controller.sendCommand("Down")
dut.controller.sendCommand("Home")
dut.controller.sendCommand("Down")
dut.controller.sendCommand("Down")
dut.controller.sendCommand("Exit")

img = dut.validator.QuickCapture("exit_image")
logger.Log("Quickcapture path {}".format(img))



dut.controller.sendCommand("Home")
dut.controller.sendCommand("Up")
dut.controller.sendCommand("Up")
dut.controller.sendCommand("Up")
dut.controller.sendCommand("Up")


img = dut.validator.QuickCapture("exit_image")
logger.Log("Quickcapture path {}".format(img))

dut.controller.sendCommand("Home")

chkpt.init("top_pick")
if(dut.validator.validateCheckPoint((chkpt))):
    dut.CommitStepResult("Checkpoint: top_pick","PASSED")
else:
    dut.CommitStepResult("Checkpoint: top_pick","FAILED")
    script_status = "FAILED"

dut.controller.sendCommand("Up")
dut.controller.sendCommand("Up")
dut.controller.sendCommand("Up")
dut.controller.sendCommand("Up")

img = dut.validator.QuickCapture("exit_image")
logger.Log("Quickcapture path {}".format(img))


dut.controller.sendCommand("Down")
dut.controller.sendCommand("Down")
dut.controller.sendCommand("Down")
dut.controller.sendCommand("Home")

dut.CommitTestResult(script_status)
