#''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
#TestCase ID:
#Description:
#Author:
#Date:
#Version:

#''''''''''''''''''''AUTOGENERATED CODE - DO NOT MODIFY''''''''''''''''''''
import clr,sys,os,time, json
clr.AddReference("ScriptingLibrary")
import ScriptingLibrary
dut = ScriptingLibrary.DUT()
logger = ScriptingLibrary.Logger()
chkpt = ScriptingLibrary.CheckPoint()
testResult = ScriptingLibrary.TestResult()
args = sys.argv
scriptPath = os.path.realpath(__file__)
remoteFiringType = "IR"
dut.Configure(args[1],args[2],args[3],args[4],scriptPath,remoteFiringType)
logger.Configure(args[1],args[2],args[3],args[4],scriptPath)

#''''''''''''''''''''''''''''''''IMPORTS''''''''''''''''''''''''''''''''''
#''''''''''''''''''''''''''''''END IMPORTS''''''''''''''''''''''''''''''''

#'''''''''''''''''''''''''END AUTOGENERATED CODE'''''''''''''''''''''''''''
#''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
config = {
"router_setting": { "name" : "Wifi_channel" , "value": { "band": "2.4GHz", "channel": 5 } },
"connection_type" : "ssh",
"connection_params" : {"port":22, "ipaddress":"192.168.30.100", "username":"admin", "password":"Falcon@123"},
"commands" : "nvram set 'wl0_chanspec=5';nvram commit;restart_wireless",
"custom_attributes" : {"execid": args[1]}
}
config = json.dumps(config)

output = dut.testEnvironmentController.ChangeRouterSettings(config)
logger.Log("Check")
print output

time.sleep(10)
config1 = {
"router_setting": { "name" : "Wifi_channel" , "value": { "band": "2.4GHz", "channel": 6 } },
"connection_type" : "ssh",
"connection_params" : {"port":22, "ipaddress":"192.168.30.100", "username":"admin", "password":"Falcon@123"},
"commands" : "nvram set 'wl0_chanspec=6';nvram commit;restart_wireless",
"custom_attributes" : {"execid": args[1]}
}

output1 = dut.testEnvironmentController.ReleaseRouterSettings(config)
#config1 = json.dumps(config1)
#output1 = dut.testEnvironmentController.ReleaseRouterSettings(config1)
print output1
#time.sleep(10)
#output = dut.testEnvironmentController.ChangeRouterSettings(config)
#logger.Log("Check")
#time.sleep(10)
#output = dut.testEnvironmentController.ReleaseRouterSettings(config)
#logger.Log("Check")
#time.sleep(10)
#output = dut.testEnvironmentController.ReleaseRouterSettings(config)
#logger.Log("Check")
#time.sleep(10)
#print output