#'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''' 
#TestCase ID: 
#Description: 
#Author: 
#Date: 
#Version: 

#''''''''''''''''''''AUTOGENERATED CODE - DO NOT MODIFY'''''''''''''''''''' 
import clr,sys,os,time, datetime
clr.AddReference("MobileScriptingLibrary") 
import MobileScriptingLibrary 
dut = MobileScriptingLibrary.MobileDUT() 
logger = MobileScriptingLibrary.Logger() 
chkpt = MobileScriptingLibrary.CheckPoint() 
config = MobileScriptingLibrary.DeviceConfig() 

#''''''''''''''''''''''''''''''''IMPORTS''''''''''''''''''''''''''''''''''' 
#''''''''''''''''''''''''''''''END IMPORTS''''''''''''''''''''''''''''''''' 

#''''''''''''''''''''''''''''''FOR iOS DEVICE'''''''''''''''''''''''''''''' 
#config.DeviceType = "iOS" 
#config.AppName = "com.google.ios.youtube" 


#''''''''''''''''''''''''''''FOR ANDROID DEVICE'''''''''''''''''''''''''''' 
config.DeviceType = "Android" 
config.AppPackage = "com.google.android.youtube" 
config.AppActivity = ".HomeActivity" 

args = sys.argv 
scriptPath = os.path.realpath(__file__) 
dut.Configure(args[1],args[2],args[3],args[4],scriptPath) 
logger.Configure(args[1],args[2],args[3],args[4],scriptPath)


def upload_ss():
    timestamp = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
    # timestamp = timestamp.replace(":", "")
    image_name = "img_{}".format(timestamp)
    img = None
    try:
        ss = dut.GetScreenshot()
        time.sleep(1)
        img = dut.validator.UploadScreenshot(image_name, ss)
        # logger.Log("Uploaded image {}".format(img))
    except Exception as e:
        logger.Error("Exception - " + str(e))
        img = None
    finally:
        return img

try: 

    if(dut.InitApp(config)): 
        logger.Log("App launched.")
        upload_ss()
        dut.CloseApp()

        for i in range(0, 10000):
            logger.Log("------------------- Iteration Count {} -------------------".format(i))
            time.sleep(2)

            config.AppPackage = "com.bskyb.nowtv.beta"
            config.AppActivity = "com.nowtv.view.activity.StartupActivity"
            init_status = dut.InitApp(config)
            logger.Log("NowTV - {}".format(init_status))
            upload_ss()
            dut.CloseApp()

            config.AppPackage = "com.bskyb.skygo"
            config.AppActivity = "com.bskyb.uma.app.bootstrap.BootstrapActivity"
            init_status = dut.InitApp(config)
            logger.Log("SkyGo - {}".format(init_status))
            upload_ss()
            dut.CloseApp()

            config.AppPackage = "com.tv.v18.viola"
            config.AppActivity = "com.tv.v18.viola.views.activities.RSHomeActivity"
            init_status = dut.InitApp(config)
            logger.Log("Voot - {}".format(init_status))
            upload_ss()
            dut.CloseApp()

            config.AppPackage = "com.google.android.youtube"
            config.AppActivity = ".HomeActivity"
            init_status = dut.InitApp(config)
            logger.Log("Youtube - {}".format(init_status))
            upload_ss()
            dut.CloseApp()


            config.AppPackage = "com.graymatrix.did"
            config.AppActivity = "com.graymatrix.did.splash.SplashActivity"
            init_status = dut.InitApp(config)
            logger.Log("Zee5 - {}".format(init_status))
            upload_ss()
            dut.CloseApp()

        
finally: 
    dut.Stop() 

#'''''''''''''''''''''''''END AUTOGENERATED CODE''''''''''''''''''''''''''' 
#''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
